In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

/tmp/ipykernel_92720/2256054893.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

In [3]:
import re
from tqdm.auto import tqdm

# Load lexicon
lex = pd.read_csv("crisis_vocabulary.csv")

terms = (
    lex["term"]
    .dropna()
    .astype(str)
    .str.lower()
    .str.strip()
    .unique()
    .tolist()
)

# Separate single words vs multi-word expressions
single_words = [t for t in terms if " " not in t]
multi_words  = [t for t in terms if " " in t]

print(f"Single words: {len(single_words)} | Multi-word phrases: {len(multi_words)}")

Single words: 70 | Multi-word phrases: 51

In [4]:
# Escape regex characters
single_words_escaped = [re.escape(w) for w in single_words]
multi_words_escaped  = [re.escape(p) for p in multi_words]

# Word-boundary pattern for single words
single_word_pattern = r"\b(" + "|".join(single_words_escaped) + r")\b"

# Phrase pattern (no word boundaries inside phrases)
multi_word_pattern = r"(" + "|".join(multi_words_escaped) + r")"

# Compile regex (case-insensitive)
single_word_regex = re.compile(single_word_pattern, flags=re.IGNORECASE)
multi_word_regex  = re.compile(multi_word_pattern, flags=re.IGNORECASE)

In [5]:
def count_profanity(text):
    if not isinstance(text, str) or not text:
        return 0

    # count single words
    single_hits = single_word_regex.findall(text)

    # count multi-word phrases
    multi_hits = multi_word_regex.findall(text)

    return len(single_hits) + len(multi_hits)


def count_distinct_profanity(text):
    if not isinstance(text, str) or not text:
        return 0

    single_hits = set(m.lower() for m in single_word_regex.findall(text))
    multi_hits  = set(m.lower() for m in multi_word_regex.findall(text))

    return len(single_hits.union(multi_hits))

In [6]:
tqdm.pandas()

df["crisis_count"] = df["text"].progress_apply(count_profanity)
df["crisis_distinct"] = df["text"].progress_apply(count_distinct_profanity)

df[["text", "crisis_count", "crisis_distinct"]].head(10)

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

,text,crisis_count,crisis_distinct
0,"When we start talking about the economy, it's ...",2,2
1,It's no secret which groups are hit the hardes...,0,0
2,How can our elderly who have worked so hard to...,0,0
3,I believe that social security is one of this ...,2,2
4,"In contrast, I am committed to an economic pro...",1,1
5,This just doesn't make sense. Older Americans ...,0,0
6,"In fact, if you look around, you'll notice tha...",0,0
7,"More important, in today's unstable economy wi...",1,1
8,"Indeed, I believe that the earnings limitation...",0,0
9,I want to thank you for this opportunity to vi...,0,0

In [7]:
df.sort_values("crisis_count", ascending=False)[
    ["speech_par_id", "name_date", "text", "crisis_count"]
].head(20)

,speech_par_id,name_date,text,crisis_count
22329,2009_11,NaN,Thirty-five years ago Franklin Roosevelt told ...,15
70748,979_998,NaN,"During the war, you remember, when we all knew...",15
39922,924_17,NaN,The American faith has been a faith in the gro...,13
17277,2581_6,NaN,We complain sometimes about interest rates--an...,12
34210,2376_10,NaN,Here are some things we should do to lower inf...,12
16506,1274_9,NaN,That is the kind of program that we should loo...,12
62050,2008-10-14-blue-bell-pennsylvania_3,2008-10-14,I will begin by making certain that the 700 bi...,11
19243,1265_6,NaN,The fact is they are trying to sell you a prog...,10
57392,2004-09-24-education-janesville-wisconsin_82,2004-09-24,"Audience member. We're praying for you, George...",10
19630,1258_6,NaN,The fact is they are trying to sell you a prog...,10
4811,2045_4,NaN,The reaction to the explosion has been fear--f...,10
48107,1755_25,NaN,The second major part of Operation Consume is ...,10
45377,1178_9,NaN,You can answer those questions once and for al...,10
58294,2004-10-20-eau-claire-wisconsin_71,2004-10-20,I saw a threat with Saddam Hussein. I saw a th...,10
1984,2244_5,NaN,Now the second pledge that the President made ...,10
56814,2004-10-22-wilkes-barre-pennsylvania_15,2004-10-22,The President. And that's pretty clear. He con...,10
55562,2004-10-24-alamogordo-new-mexico_11,2004-10-24,The President. ——end quote. And that's pretty ...,9
66278,2004-09-20-new-york-university_6,2004-09-20,National security is a central issue in this c...,9
36176,1871_26,NaN,"I have traveled a great deal, as you know perh...",9
55434,2004-10-21-hershey-pennsylvania-0_57,2004-10-21,Audience members. Boo-o-o! The President. His ...,9

In [8]:
df["crisis_count"].describe()

count    71808.000000
mean         0.371686
std          0.864065
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         15.000000
Name: crisis_count, dtype: float64

In [9]:
df["word_count"] = df["text"].str.split().str.len()
df["crisis_per_100w"] = (
    df["crisis_count"] / df["word_count"] * 100
).fillna(0)

In [10]:
df["crisis_per_100w"].describe()

count    71808.000000
mean         0.423953
std          1.029253
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         17.647059
Name: crisis_per_100w, dtype: float64

In [11]:
df["election_year"] = df["election_date"].astype(str).str[:4].astype("Int64")

In [12]:
set(df["election_year"])

{1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020}

In [13]:
df["person"] = (
    df["person"].astype(str)
    + "_"
    + df["election_year"].astype(str)
)

In [14]:
df_pop = df[df["Populism"] == 1]
df_non = df[df["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)

Populist rows: 1861

In [15]:
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

1    1861
0    1861
Name: Populism, dtype: int64

In [16]:
df_balanced[["crisis_per_100w", "Populism"]].groupby("Populism").describe()

         crisis_per_100w
                   count      mean       std  min  25%  50%  75%        max
Populism
0                 1861.0  0.413311  1.027229  0.0  0.0  0.0  0.0  11.111111
1                 1861.0  0.299126  0.794803  0.0  0.0  0.0  0.0   9.375000

In [17]:
import statsmodels.api as sm

y = df_balanced["crisis_per_100w"]
X = df_balanced[["Populism"]]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit(cov_type="HC3")
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        crisis_per_100w   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     14.38
Date:                Mon, 15 Dec 2025   Prob (F-statistic):           0.000152
Time:                        17:09:58   Log-Likelihood:                -4963.5
No. Observations:                3722   AIC:                             9931.
Df Residuals:                    3720   BIC:                             9943.
Df Model:                           1
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4133      0.024     17.353      0.000       0.367       0.460
Populism      -0.1142      0.030     -3.792      0.000      -0.173      -0.055
==============================================================================
Omnibus:                     3071.526   Durbin-Watson:                   1.891
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            79528.956
Skew:                           3.867   Prob(JB):                         0.00
Kurtosis:                      24.283   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [18]:
import numpy as np
coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["crisis_per_100w"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit(cov_type="HC3")
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(-0.12414623685164951, 0.0231076207421135)

In [21]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

fe = smf.ols(
    "crisis_per_100w ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        crisis_per_100w   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     2.350
Date:                Mon, 15 Dec 2025   Prob (F-statistic):              0.135
Time:                        17:09:59   Log-Likelihood:                -4914.6
No. Observations:                3722   AIC:                             9899.
Df Residuals:                    3687   BIC:                         1.012e+04
Df Model:                          34
Covariance Type:              cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.6519      0.014     47.389      0.000       0.625       0.679
C(person)[T.Bush_1988]          -0.4518      0.008    -56.971      0.000      -0.467      -0.436
C(person)[T.Bush_1992]          -0.2180      0.011    -20.657      0.000      -0.239      -0.197
C(person)[T.Bush_2004]           0.0442      0.009      4.817      0.000       0.026       0.062
C(person)[T.Carter_1976]        -0.2370      0.012    -20.208      0.000      -0.260      -0.214
C(person)[T.Carter_1980]        -0.0694      0.007    -10.300      0.000      -0.083      -0.056
C(person)[T.Clinton_1992]       -0.3309      0.008    -42.852      0.000      -0.346      -0.316
C(person)[T.Clinton_1996]       -0.1553      0.006    -25.394      0.000      -0.167      -0.143
C(person)[T.Clinton_2016]       -0.3096      0.002   -168.728      0.000      -0.313      -0.306
C(person)[T.Dole_1996]          -0.3620      0.006    -61.047      0.000      -0.374      -0.350
C(person)[T.Dukakis_1988]       -0.2948      0.007    -42.896      0.000      -0.308      -0.281
C(person)[T.Eisenhower_1952]    -0.2659      0.020    -13.280      0.000      -0.305      -0.227
C(person)[T.Eisenhower_1956]     0.2130      0.003     66.942      0.000       0.207       0.219
C(person)[T.Ford_1976]           0.4472      0.001    413.776      0.000       0.445       0.449
C(person)[T.Gore_2000]          -0.2369      0.020    -11.950      0.000      -0.276      -0.198
C(person)[T.Humphrey_1968]      -0.2404      0.008    -29.592      0.000      -0.256      -0.224
C(person)[T.Johnson_1964]       -0.0434      0.007     -5.922      0.000      -0.058      -0.029
C(person)[T.Kennedy_1960]       -0.3525      0.011    -31.938      0.000      -0.374      -0.331
C(person)[T.Kerry_2004]         -0.1493      0.013    -11.271      0.000      -0.175      -0.123
C(person)[T.McCain_2008]         0.0299      0.020      1.512      0.130      -0.009       0.069
C(person)[T.McGovern_1972]      -0.1772      0.021     -8.403      0.000      -0.219      -0.136
C(person)[T.Mondale_1984]       -0.4679      0.003   -152.886      0.000      -0.474      -0.462
C(person)[T.Nixon_1960]         -0.3740      0.009    -41.178      0.000      -0.392      -0.356
C(person)[T.Nixon_1968]         -0.0718      0.007     -9.853      0.000      -0.086      -0.057
C(person)[T.Nixon_1972]         -0.1455      0.000   -304.442      0.000      -0.146      -0.145
C(person)[T.Obama_2008]          0.1471      0.022      6.598      0.000       0.103       0.191
C(person)[T.Obama_2012]         -0.1408      0.011    -12.791      0.000      -0.162      -0.119
C(person)[T.Reagan_1980]         0.0152      0.000     38.874      0.000       0.014       0.016
C(person)[T.Reagan_1984]        -0.0670      0.005    -13.725      0.000      -0.077      -0.057
C(person)[T.Romney_2012]        -0.2811      0.010    -27.449      0.000      -0.301      -0.261
C(person)[T.Stevenson_1952]     -0.2006      0.001   -172.571      0.000      -0.203      -0.198
C(person)[T.Stevenson_1956]     -0.1922      0.012    -15.671      0.000      -0.216      -0.168
C(person)[T.Trump_2016]         -0.2234      0.023     -9.623      0.000      -0.269      -0.178
C(person)[T.Trump_2020]         -0.0581      0.003    -19.783      0.000      -0.064      -0.052
Populism                        -0.1582      0.041     -3.880      0.000      -0.238      -0.078
prior_president                 -0.1931      0.004    -51.100      0.000      -0.200      -0.186
==============================================================================
Omnibus:                     3001.376   Durbin-Watson:                   1.907
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            75535.638
Skew:                           3.741   Prob(JB):                         0.00
Kurtosis:                      23.762   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

In [24]:
df.to_csv("prof_llm_crisis.csv", encoding="utf-8", index=False)

In [25]:
dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_crisis_with_similarity.csv", encoding="utf-8")

/tmp/ipykernel_92720/905135519.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_crisis_with_similarity.csv", encoding="utf-8")

In [27]:
df_pop = dfllm[dfllm["Populism"] == 1]
df_non = dfllm[dfllm["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

1    1861
0    1861
Name: Populism, dtype: int64

In [28]:
df_balanced[["agg_sim_top10", "agg_sim_max"]].describe()
df_balanced[["agg_sim_top10", "agg_sim_max"]].corr()

               agg_sim_top10  agg_sim_max
agg_sim_top10       1.000000     0.874727
agg_sim_max         0.874727     1.000000

In [29]:
for var in ["agg_sim_top10", "agg_sim_max"]:
    res = smf.ols(
        f"{var} ~ Populism + prior_president + C(person)",
        data=df_balanced
    ).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})
    print(var, res.params["Populism"], res.pvalues["Populism"])

agg_sim_top10 0.0008397147923138562 0.7640035184496927
agg_sim_max 0.0028521628973474994 0.4998764689940214

In [30]:
import statsmodels.api as sm

y = df_balanced["agg_sim_top10"]
X = sm.add_constant(df_balanced[["Populism"]])

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          agg_sim_top10   R-squared:                       0.009
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     34.92
Date:                Mon, 15 Dec 2025   Prob (F-statistic):           3.75e-09
Time:                        17:14:04   Log-Likelihood:                 5370.9
No. Observations:                3722   AIC:                        -1.074e+04
Df Residuals:                    3720   BIC:                        -1.073e+04
Df Model:                           1
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2215      0.001    167.849      0.000       0.219       0.224
Populism       0.0111      0.002      5.909      0.000       0.007       0.015
==============================================================================
Omnibus:                      368.932   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              681.167
Skew:                           0.669   Prob(JB):                    1.22e-148
Kurtosis:                       4.614   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [31]:
import numpy as np

coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["agg_sim_top10"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit()
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(0.011351471881217046, 0.0013652696636697705)

In [32]:
import statsmodels.api as sm

y = df_balanced["agg_sim_top10"]

X = df_balanced[["Populism", "prior_president"]]
X = sm.add_constant(X)

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          agg_sim_top10   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     18.78
Date:                Mon, 15 Dec 2025   Prob (F-statistic):           7.65e-09
Time:                        17:14:16   Log-Likelihood:                 5372.6
No. Observations:                3722   AIC:                        -1.074e+04
Df Residuals:                    3719   BIC:                        -1.072e+04
Df Model:                           2
Covariance Type:                  HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.2231      0.002    141.364      0.000       0.220       0.226
Populism            0.0100      0.002      5.222      0.000       0.006       0.014
prior_president    -0.0040      0.002     -1.960      0.050      -0.008    1.29e-07
==============================================================================
Omnibus:                      363.922   Durbin-Watson:                   1.788
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              670.501
Skew:                           0.662   Prob(JB):                    2.53e-146
Kurtosis:                       4.603   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [33]:
import statsmodels.formula.api as smf

fe_person = smf.ols(
    "agg_sim_top10 ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe_person.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          agg_sim_top10   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.085
Method:                 Least Squares   F-statistic:                     8.584
Date:                Mon, 15 Dec 2025   Prob (F-statistic):            0.00611
Time:                        17:14:30   Log-Likelihood:                 5535.8
No. Observations:                3722   AIC:                        -1.100e+04
Df Residuals:                    3687   BIC:                        -1.078e+04
Df Model:                          34
Covariance Type:              cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.2329      0.001    246.867      0.000       0.231       0.235
C(person)[T.Bush_1988]          -0.0125      0.001    -22.981      0.000      -0.014      -0.011
C(person)[T.Bush_1992]          -0.0007      0.001     -1.021      0.307      -0.002       0.001
C(person)[T.Bush_2004]          -0.0039      0.001     -6.143      0.000      -0.005      -0.003
C(person)[T.Carter_1976]         0.0002      0.001      0.190      0.850      -0.001       0.002
C(person)[T.Carter_1980]        -0.0085      0.000    -18.469      0.000      -0.009      -0.008
C(person)[T.Clinton_1992]       -0.0133      0.001    -25.181      0.000      -0.014      -0.012
C(person)[T.Clinton_1996]       -0.0054      0.000    -12.819      0.000      -0.006      -0.005
C(person)[T.Clinton_2016]       -0.0213      0.000   -169.558      0.000      -0.022      -0.021
C(person)[T.Dole_1996]          -0.0201      0.000    -49.392      0.000      -0.021      -0.019
C(person)[T.Dukakis_1988]       -0.0156      0.000    -33.146      0.000      -0.017      -0.015
C(person)[T.Eisenhower_1952]    -0.0041      0.001     -2.999      0.003      -0.007      -0.001
C(person)[T.Eisenhower_1956]     0.0275      0.000    125.843      0.000       0.027       0.028
C(person)[T.Ford_1976]           0.0064   7.41e-05     86.238      0.000       0.006       0.007
C(person)[T.Gore_2000]          -0.0264      0.001    -19.436      0.000      -0.029      -0.024
C(person)[T.Humphrey_1968]      -0.0274      0.001    -49.114      0.000      -0.028      -0.026
C(person)[T.Johnson_1964]       -0.0049      0.001     -9.664      0.000      -0.006      -0.004
C(person)[T.Kennedy_1960]       -0.0081      0.001    -10.660      0.000      -0.010      -0.007
C(person)[T.Kerry_2004]         -0.0032      0.001     -3.545      0.000      -0.005      -0.001
C(person)[T.McCain_2008]         0.0451      0.001     33.300      0.000       0.042       0.048
C(person)[T.McGovern_1972]       0.0044      0.001      3.038      0.002       0.002       0.007
C(person)[T.Mondale_1984]       -0.0096      0.000    -45.520      0.000      -0.010      -0.009
C(person)[T.Nixon_1960]         -0.0281      0.001    -45.053      0.000      -0.029      -0.027
C(person)[T.Nixon_1968]         -0.0012      0.000     -2.479      0.013      -0.002      -0.000
C(person)[T.Nixon_1972]         -0.0114   3.28e-05   -347.999      0.000      -0.011      -0.011
C(person)[T.Obama_2008]          0.0421      0.002     27.561      0.000       0.039       0.045
C(person)[T.Obama_2012]          0.0022      0.001      2.952      0.003       0.001       0.004
C(person)[T.Reagan_1980]         0.0065   2.68e-05    242.723      0.000       0.006       0.007
C(person)[T.Reagan_1984]        -0.0031      0.000     -9.117      0.000      -0.004      -0.002
C(person)[T.Romney_2012]         0.0016      0.001      2.216      0.027       0.000       0.003
C(person)[T.Stevenson_1952]     -0.0303   7.97e-05   -379.452      0.000      -0.030      -0.030
C(person)[T.Stevenson_1956]     -0.0100      0.001    -11.851      0.000      -0.012      -0.008
C(person)[T.Trump_2016]         -0.0124      0.002     -7.777      0.000      -0.016      -0.009
C(person)[T.Trump_2020]         -0.0077      0.000    -38.480      0.000      -0.008      -0.007
Populism                         0.0008      0.003      0.300      0.764      -0.005       0.006
prior_president                 -0.0095      0.000    -36.702      0.000      -0.010      -0.009
==============================================================================
Omnibus:                      159.438   Durbin-Watson:                   1.864
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              225.945
Skew:                           0.412   Prob(JB):                     8.64e-50
Kurtosis:                       3.882   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

# Real/Constructed Crises

In [34]:
df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

/tmp/ipykernel_92720/2256054893.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

In [36]:
TEXT_COL = "text"

REAL_LEX_PATH = "real_crisis.csv"           # column: term
CONSTR_LEX_PATH = "constructed_crisis.csv"  # column: term


# -----------------------------
# 1) Load lexicons (robust)
# -----------------------------
def load_term_list(path: str) -> list[str]:
    lex_raw = pd.read_csv(path, encoding="utf-8-sig", low_memory=False)

    # If the file got read as a single column (weird header), recover a "term" column
    if lex_raw.shape[1] == 1:
        only_col = lex_raw.columns[0]
        s = lex_raw[only_col].astype(str)

        tmp = (
            s.str.replace("\ufeff", "", regex=False)
             .str.replace('"', "", regex=False)
             .str.strip()
             .str.split(r"[,\t;]", n=1, expand=True)[0]
             .to_frame(name="term")
        )
        tmp["term"] = tmp["term"].astype(str).str.strip()
        tmp = tmp[tmp["term"].str.lower().ne("term") & tmp["term"].ne("")]
        lex = tmp.copy()
    else:
        lex_raw.columns = [c.strip().replace("\ufeff", "") for c in lex_raw.columns]
        if "term" not in lex_raw.columns:
            raise ValueError(f"{path}: expected a 'term' column, found {lex_raw.columns.tolist()}")
        lex = lex_raw.copy()

    terms = (
        lex["term"]
        .dropna()
        .astype(str)
        .str.lower()
        .str.strip()
        .unique()
        .tolist()
    )
    return terms


real_terms = load_term_list(REAL_LEX_PATH)
constr_terms = load_term_list(CONSTR_LEX_PATH)

print(f"Real-crisis terms: {len(real_terms)} | Constructed-crisis terms: {len(constr_terms)}")


# -----------------------------
# 2) Build regex counters (single vs phrases)
# -----------------------------
def build_regexes(terms: list[str]):
    single_words = [t for t in terms if " " not in t]
    multi_words  = [t for t in terms if " " in t]

    single_words_escaped = [re.escape(w) for w in single_words]
    multi_words_escaped  = [re.escape(p) for p in multi_words]

    single_word_regex = (
        re.compile(r"\b(" + "|".join(single_words_escaped) + r")\b", flags=re.IGNORECASE)
        if single_words_escaped else None
    )
    multi_word_regex = (
        re.compile(r"(" + "|".join(multi_words_escaped) + r")", flags=re.IGNORECASE)
        if multi_words_escaped else None
    )

    return single_word_regex, multi_word_regex, len(single_words), len(multi_words)


real_single_re, real_multi_re, n_real_single, n_real_multi = build_regexes(real_terms)
con_single_re, con_multi_re, n_con_single, n_con_multi = build_regexes(constr_terms)

print(f"Real: single={n_real_single}, phrases={n_real_multi}")
print(f"Constructed: single={n_con_single}, phrases={n_con_multi}")


def count_hits(text, single_re, multi_re):
    if not isinstance(text, str) or not text:
        return 0
    single_hits = single_re.findall(text) if single_re else []
    multi_hits  = multi_re.findall(text) if multi_re else []
    return len(single_hits) + len(multi_hits)


def count_distinct_hits(text, single_re, multi_re):
    if not isinstance(text, str) or not text:
        return 0
    single_hits = set(m.lower() for m in single_re.findall(text)) if single_re else set()
    multi_hits  = set(m.lower() for m in multi_re.findall(text)) if multi_re else set()
    return len(single_hits.union(multi_hits))


# -----------------------------
# 3) Apply to dataframe
# -----------------------------
tqdm.pandas()

df["real_crisis_count"] = df[TEXT_COL].progress_apply(lambda t: count_hits(t, real_single_re, real_multi_re))
df["real_crisis_distinct"] = df[TEXT_COL].progress_apply(lambda t: count_distinct_hits(t, real_single_re, real_multi_re))

df["constructed_crisis_count"] = df[TEXT_COL].progress_apply(lambda t: count_hits(t, con_single_re, con_multi_re))
df["constructed_crisis_distinct"] = df[TEXT_COL].progress_apply(lambda t: count_distinct_hits(t, con_single_re, con_multi_re))

# Normalize per 100 words (like you did before)
df["word_count"] = df[TEXT_COL].fillna("").astype(str).str.split().str.len().clip(lower=1)

df["real_crisis_per_100w"] = (df["real_crisis_count"] / df["word_count"] * 100).fillna(0)
df["constructed_crisis_per_100w"] = (df["constructed_crisis_count"] / df["word_count"] * 100).fillna(0)

# Key rhetorical indicator: crisis inflation / constructed emphasis
df["constructed_minus_real_per_100w"] = df["constructed_crisis_per_100w"] - df["real_crisis_per_100w"]

# Quick check
df[[TEXT_COL,
    "real_crisis_count","constructed_crisis_count",
    "real_crisis_per_100w","constructed_crisis_per_100w",
    "constructed_minus_real_per_100w"]].head(10)

# Top examples
df.sort_values("constructed_crisis_count", ascending=False)[
    ["speech_par_id", "name_date", TEXT_COL, "constructed_crisis_count", "constructed_crisis_per_100w"]
].head(20)

df.sort_values("real_crisis_count", ascending=False)[
    ["speech_par_id", "name_date", TEXT_COL, "real_crisis_count", "real_crisis_per_100w"]
].head(20)

Real-crisis terms: 35 | Constructed-crisis terms: 27
Real: single=14, phrases=21
Constructed: single=4, phrases=23

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

,speech_par_id,name_date,text,real_crisis_count,real_crisis_per_100w
34210,2376_10,NaN,Here are some things we should do to lower inf...,12,4.225352
17277,2581_6,NaN,We complain sometimes about interest rates--an...,11,4.545455
45377,1178_9,NaN,You can answer those questions once and for al...,9,6.976744
29530,2371_13,NaN,The reason unemployment remains high is that t...,9,6.521739
1984,2244_5,NaN,Now the second pledge that the President made ...,9,3.114187
70748,979_998,NaN,"During the war, you remember, when we all knew...",8,0.506329
36176,1871_26,NaN,"I have traveled a great deal, as you know perh...",8,3.404255
42442,3226_48,NaN,Last spring we announced that we would work to...,7,5.185185
10281,2254_5,NaN,Now what is it that keeps a great and decent c...,7,2.430556
5666,2455_12,NaN,Listen to what Prime Minister Jim Callaghan of...,7,3.910615
29479,2365_10,NaN,"Under Johnson and Kennedy, the inflation rate ...",7,7.692308
21276,2196_16,NaN,This is the cause of inflation and a major cau...,7,5.343511
27980,2204_14,NaN,"Now, my friends, with regard to the war in Vie...",7,4.347826
11272,2255_2,NaN,I have heard this slogan too about the Nixon-A...,7,1.886792
15679,1843_10,NaN,Now my last point. Let's talk a little about ...,7,2.661597
46995,1026_9,NaN,There are men in our country of little faith w...,7,3.783784
5742,1821_11,NaN,I have seen what war does. I have been abroad...,7,4.794521
57811,2004-10-15-rapids-iowa-2_57,2004-10-15,I believe in the transformational power of lib...,6,7.058824
870,2245_3,NaN,Now I think that is one of the essential diffe...,6,3.157895
12710,1854_29,NaN,I have traveled to fifty-five countries since ...,6,4.651163

In [37]:
df["election_year"] = df["election_date"].astype(str).str[:4].astype("Int64")

df["person"] = (
    df["person"].astype(str)
    + "_"
    + df["election_year"].astype(str)
)

df_pop = df[df["Populism"] == 1]
df_non = df[df["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)

df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

Populist rows: 1861
1    1861
0    1861
Name: Populism, dtype: int64

# Real Crises

In [38]:
import statsmodels.api as sm

y = df_balanced["real_crisis_per_100w"]
X = df_balanced[["Populism"]]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit(cov_type="HC3")
print(model.summary())

                             OLS Regression Results
================================================================================
Dep. Variable:     real_crisis_per_100w   R-squared:                       0.007
Model:                              OLS   Adj. R-squared:                  0.006
Method:                   Least Squares   F-statistic:                     24.34
Date:                  Wed, 17 Dec 2025   Prob (F-statistic):           8.41e-07
Time:                          18:18:04   Log-Likelihood:                -2976.6
No. Observations:                  3722   AIC:                             5957.
Df Residuals:                      3720   BIC:                             5970.
Df Model:                             1
Covariance Type:                    HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1867      0.015     12.480      0.000       0.157       0.216
Populism      -0.0871      0.018     -4.934      0.000      -0.122      -0.053
==============================================================================
Omnibus:                     3706.365   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           160005.124
Skew:                           4.994   Prob(JB):                         0.00
Kurtosis:                      33.528   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [39]:
import numpy as np
coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["real_crisis_per_100w"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit(cov_type="HC3")
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(-0.08443307444891061, 0.013156630184129242)

In [40]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

fe = smf.ols(
    "real_crisis_per_100w ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe.summary())

                             OLS Regression Results
================================================================================
Dep. Variable:     real_crisis_per_100w   R-squared:                       0.033
Model:                              OLS   Adj. R-squared:                  0.024
Method:                   Least Squares   F-statistic:                     29.14
Date:                  Wed, 17 Dec 2025   Prob (F-statistic):           5.69e-06
Time:                          18:21:38   Log-Likelihood:                -2925.5
No. Observations:                  3722   AIC:                             5921.
Df Residuals:                      3687   BIC:                             6139.
Df Model:                            34
Covariance Type:                cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.3637      0.008     48.467      0.000       0.349       0.378
C(person)[T.Bush_1988]          -0.2497      0.004    -57.704      0.000      -0.258      -0.241
C(person)[T.Bush_1992]          -0.1111      0.006    -19.304      0.000      -0.122      -0.100
C(person)[T.Bush_2004]          -0.0346      0.005     -6.901      0.000      -0.044      -0.025
C(person)[T.Carter_1976]        -0.1154      0.006    -18.032      0.000      -0.128      -0.103
C(person)[T.Carter_1980]         0.0116      0.004      3.158      0.002       0.004       0.019
C(person)[T.Clinton_1992]       -0.2152      0.004    -51.076      0.000      -0.223      -0.207
C(person)[T.Clinton_1996]       -0.0768      0.003    -23.027      0.000      -0.083      -0.070
C(person)[T.Clinton_2016]       -0.2781      0.001   -277.802      0.000      -0.280      -0.276
C(person)[T.Dole_1996]          -0.2467      0.003    -76.273      0.000      -0.253      -0.240
C(person)[T.Dukakis_1988]       -0.1822      0.004    -48.600      0.000      -0.190      -0.175
C(person)[T.Eisenhower_1952]    -0.1837      0.011    -16.817      0.000      -0.205      -0.162
C(person)[T.Eisenhower_1956]     0.0379      0.002     21.854      0.000       0.035       0.041
C(person)[T.Ford_1976]           0.4139      0.001    701.884      0.000       0.413       0.415
C(person)[T.Gore_2000]          -0.2007      0.011    -18.559      0.000      -0.222      -0.180
C(person)[T.Humphrey_1968]      -0.2078      0.004    -46.906      0.000      -0.217      -0.199
C(person)[T.Johnson_1964]       -0.1343      0.004    -33.570      0.000      -0.142      -0.126
C(person)[T.Kennedy_1960]       -0.3199      0.006    -53.136      0.000      -0.332      -0.308
C(person)[T.Kerry_2004]         -0.2145      0.007    -29.691      0.000      -0.229      -0.200
C(person)[T.McCain_2008]        -0.1928      0.011    -17.887      0.000      -0.214      -0.172
C(person)[T.McGovern_1972]      -0.0402      0.012     -3.497      0.000      -0.063      -0.018
C(person)[T.Mondale_1984]       -0.2686      0.002   -160.884      0.000      -0.272      -0.265
C(person)[T.Nixon_1960]         -0.1663      0.005    -33.564      0.000      -0.176      -0.157
C(person)[T.Nixon_1968]         -0.0128      0.004     -3.229      0.001      -0.021      -0.005
C(person)[T.Nixon_1972]         -0.0985      0.000   -377.822      0.000      -0.099      -0.098
C(person)[T.Obama_2008]         -0.1368      0.012    -11.246      0.000      -0.161      -0.113
C(person)[T.Obama_2012]         -0.0663      0.006    -11.034      0.000      -0.078      -0.054
C(person)[T.Reagan_1980]        -0.0933      0.000   -437.444      0.000      -0.094      -0.093
C(person)[T.Reagan_1984]         0.0103      0.003      3.877      0.000       0.005       0.016
C(person)[T.Romney_2012]        -0.1933      0.006    -34.603      0.000      -0.204      -0.182
C(person)[T.Stevenson_1952]     -0.1477      0.001   -232.879      0.000      -0.149      -0.146
C(person)[T.Stevenson_1956]     -0.1761      0.007    -26.329      0.000      -0.189      -0.163
C(person)[T.Trump_2016]         -0.2379      0.013    -18.785      0.000      -0.263      -0.213
C(person)[T.Trump_2020]         -0.0878      0.002    -54.834      0.000      -0.091      -0.085
Populism                        -0.0913      0.022     -4.105      0.000      -0.135      -0.048
prior_president                 -0.1357      0.002    -65.813      0.000      -0.140      -0.132
==============================================================================
Omnibus:                     3605.844   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           145735.929
Skew:                           4.796   Prob(JB):                         0.00
Kurtosis:                      32.116   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

# Constructed Crises

In [41]:
import statsmodels.api as sm

y = df_balanced["constructed_crisis_count"]
X = df_balanced[["Populism"]]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit(cov_type="HC3")
print(model.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     constructed_crisis_count   R-squared:                       0.000
Model:                                  OLS   Adj. R-squared:                 -0.000
Method:                       Least Squares   F-statistic:                    0.2231
Date:                      Wed, 17 Dec 2025   Prob (F-statistic):              0.637
Time:                              18:21:46   Log-Likelihood:                 4650.0
No. Observations:                      3722   AIC:                            -9296.
Df Residuals:                          3720   BIC:                            -9284.
Df Model:                                 1
Covariance Type:                        HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0054      0.002      3.169      0.002       0.002       0.009
Populism      -0.0011      0.002     -0.472      0.637      -0.006       0.003
==============================================================================
Omnibus:                     6944.266   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6439284.030
Skew:                          14.274   Prob(JB):                         0.00
Kurtosis:                     204.758   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [42]:
import numpy as np
coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["constructed_crisis_count"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit(cov_type="HC3")
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(-0.0008597528210640012, 0.0017026307918060143)

In [43]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

fe = smf.ols(
    "constructed_crisis_count ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     constructed_crisis_count   R-squared:                       0.010
Model:                                  OLS   Adj. R-squared:                  0.001
Method:                       Least Squares   F-statistic:                   0.01219
Date:                      Wed, 17 Dec 2025   Prob (F-statistic):              0.913
Time:                              18:21:53   Log-Likelihood:                 4668.3
No. Observations:                      3722   AIC:                            -9267.
Df Residuals:                          3687   BIC:                            -9049.
Df Model:                                34
Covariance Type:                    cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.0132      0.001     14.194      0.000       0.011       0.015
C(person)[T.Bush_1988]          -0.0127      0.001    -23.679      0.000      -0.014      -0.012
C(person)[T.Bush_1992]           0.0057      0.001      7.906      0.000       0.004       0.007
C(person)[T.Bush_2004]          -0.0100      0.001    -16.121      0.000      -0.011      -0.009
C(person)[T.Carter_1976]         0.0046      0.001      5.777      0.000       0.003       0.006
C(person)[T.Carter_1980]        -0.0098      0.000    -21.497      0.000      -0.011      -0.009
C(person)[T.Clinton_1992]       -0.0114      0.001    -21.722      0.000      -0.012      -0.010
C(person)[T.Clinton_1996]       -0.0098      0.000    -23.569      0.000      -0.011      -0.009
C(person)[T.Clinton_2016]       -0.0119      0.000    -95.512      0.000      -0.012      -0.012
C(person)[T.Dole_1996]          -0.0029      0.000     -7.241      0.000      -0.004      -0.002
C(person)[T.Dukakis_1988]       -0.0115      0.000    -24.565      0.000      -0.012      -0.011
C(person)[T.Eisenhower_1952]    -0.0076      0.001     -5.584      0.000      -0.010      -0.005
C(person)[T.Eisenhower_1956]     0.0238      0.000    110.348      0.000       0.023       0.024
C(person)[T.Ford_1976]           0.0270   7.33e-05    368.621      0.000       0.027       0.027
C(person)[T.Gore_2000]          -0.0103      0.001     -7.678      0.000      -0.013      -0.008
C(person)[T.Humphrey_1968]      -0.0128      0.001    -23.150      0.000      -0.014      -0.012
C(person)[T.Johnson_1964]       -0.0099      0.000    -19.862      0.000      -0.011      -0.009
C(person)[T.Kennedy_1960]       -0.0130      0.001    -17.374      0.000      -0.014      -0.012
C(person)[T.Kerry_2004]         -0.0109      0.001    -12.130      0.000      -0.013      -0.009
C(person)[T.McCain_2008]        -0.0004      0.001     -0.321      0.748      -0.003       0.002
C(person)[T.McGovern_1972]      -0.0058      0.001     -4.061      0.000      -0.009      -0.003
C(person)[T.Mondale_1984]        0.0041      0.000     19.651      0.000       0.004       0.004
C(person)[T.Nixon_1960]         -0.0128      0.001    -20.836      0.000      -0.014      -0.012
C(person)[T.Nixon_1968]         -0.0127      0.000    -25.669      0.000      -0.014      -0.012
C(person)[T.Nixon_1972]         -0.0092   3.24e-05   -283.864      0.000      -0.009      -0.009
C(person)[T.Obama_2008]         -0.0101      0.002     -6.686      0.000      -0.013      -0.007
C(person)[T.Obama_2012]         -0.0024      0.001     -3.267      0.001      -0.004      -0.001
C(person)[T.Reagan_1980]        -0.0120   2.65e-05   -452.978      0.000      -0.012      -0.012
C(person)[T.Reagan_1984]         0.0005      0.000      1.589      0.112      -0.000       0.001
C(person)[T.Romney_2012]        -0.0129      0.001    -18.626      0.000      -0.014      -0.012
C(person)[T.Stevenson_1952]     -0.0119   7.88e-05   -151.540      0.000      -0.012      -0.012
C(person)[T.Stevenson_1956]     -0.0015      0.001     -1.753      0.080      -0.003       0.000
C(person)[T.Trump_2016]         -0.0010      0.002     -0.632      0.528      -0.004       0.002
C(person)[T.Trump_2020]         -0.0090      0.000    -45.151      0.000      -0.009      -0.009
Populism                        -0.0035      0.003     -1.281      0.200      -0.009       0.002
prior_president                 -0.0031      0.000    -12.224      0.000      -0.004      -0.003
==============================================================================
Omnibus:                     6895.924   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6197105.538
Skew:                          14.066   Prob(JB):                         0.00
Kurtosis:                     200.910   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

# LLM

In [44]:
dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_crisis_with_similarity_real_constructed.csv", encoding="utf-8")

/tmp/ipykernel_92720/2267522352.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_crisis_with_similarity_real_constructed.csv", encoding="utf-8")

In [45]:
df_pop = dfllm[dfllm["Populism"] == 1]
df_non = dfllm[dfllm["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

Populist rows: 1861
1    1861
0    1861
Name: Populism, dtype: int64

# Real

In [46]:
import statsmodels.api as sm

y = df_balanced["real_sim_top10"]
X = sm.add_constant(df_balanced[["Populism"]])

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         real_sim_top10   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     36.89
Date:                Wed, 17 Dec 2025   Prob (F-statistic):           1.38e-09
Time:                        18:34:24   Log-Likelihood:                 4738.1
No. Observations:                3722   AIC:                            -9472.
Df Residuals:                    3720   BIC:                            -9460.
Df Model:                           1
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1816      0.002    119.234      0.000       0.179       0.185
Populism       0.0135      0.002      6.073      0.000       0.009       0.018
==============================================================================
Omnibus:                      306.600   Durbin-Watson:                   1.749
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              495.646
Skew:                           0.618   Prob(JB):                    2.35e-108
Kurtosis:                       4.291   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [47]:
import numpy as np

coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["real_sim_top10"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit()
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(0.013904527289780729, 0.0015195562350492138)

In [48]:
import statsmodels.api as sm

y = df_balanced["real_sim_top10"]

X = df_balanced[["Populism", "prior_president"]]
X = sm.add_constant(X)

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         real_sim_top10   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     18.69
Date:                Wed, 17 Dec 2025   Prob (F-statistic):           8.35e-09
Time:                        18:34:34   Log-Likelihood:                 4738.5
No. Observations:                3722   AIC:                            -9471.
Df Residuals:                    3719   BIC:                            -9452.
Df Model:                           2
Covariance Type:                  HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.1826      0.002     99.518      0.000       0.179       0.186
Populism            0.0128      0.002      5.639      0.000       0.008       0.017
prior_president    -0.0025      0.002     -1.048      0.295      -0.007       0.002
==============================================================================
Omnibus:                      303.370   Durbin-Watson:                   1.749
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              488.920
Skew:                           0.614   Prob(JB):                    6.80e-107
Kurtosis:                       4.282   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [49]:
import statsmodels.formula.api as smf

fe_person = smf.ols(
    "real_sim_top10 ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe_person.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         real_sim_top10   R-squared:                       0.123
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     25.62
Date:                Wed, 17 Dec 2025   Prob (F-statistic):           1.54e-05
Time:                        18:34:37   Log-Likelihood:                 4963.1
No. Observations:                3722   AIC:                            -9856.
Df Residuals:                    3687   BIC:                            -9638.
Df Model:                          34
Covariance Type:              cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.1901      0.001    165.313      0.000       0.188       0.192
C(person)[T.Bush_1988]          -0.0107      0.001    -16.116      0.000      -0.012      -0.009
C(person)[T.Bush_1992]          -0.0019      0.001     -2.205      0.027      -0.004      -0.000
C(person)[T.Bush_2004]          -0.0078      0.001    -10.108      0.000      -0.009      -0.006
C(person)[T.Carter_1976]         0.0015      0.001      1.518      0.129      -0.000       0.003
C(person)[T.Carter_1980]        -0.0048      0.001     -8.490      0.000      -0.006      -0.004
C(person)[T.Clinton_1992]       -0.0049      0.001     -7.524      0.000      -0.006      -0.004
C(person)[T.Clinton_1996]       -0.0088      0.001    -17.199      0.000      -0.010      -0.008
C(person)[T.Clinton_2016]       -0.0213      0.000   -138.866      0.000      -0.022      -0.021
C(person)[T.Dole_1996]          -0.0223      0.000    -44.932      0.000      -0.023      -0.021
C(person)[T.Dukakis_1988]       -0.0107      0.001    -18.552      0.000      -0.012      -0.010
C(person)[T.Eisenhower_1952]    -0.0102      0.002     -6.122      0.000      -0.014      -0.007
C(person)[T.Eisenhower_1956]     0.0241      0.000     90.710      0.000       0.024       0.025
C(person)[T.Ford_1976]           0.0116   9.04e-05    128.253      0.000       0.011       0.012
C(person)[T.Gore_2000]          -0.0174      0.002    -10.481      0.000      -0.021      -0.014
C(person)[T.Humphrey_1968]      -0.0288      0.001    -42.481      0.000      -0.030      -0.028
C(person)[T.Johnson_1964]       -0.0110      0.001    -17.963      0.000      -0.012      -0.010
C(person)[T.Kennedy_1960]       -0.0113      0.001    -12.273      0.000      -0.013      -0.010
C(person)[T.Kerry_2004]          0.0105      0.001      9.438      0.000       0.008       0.013
C(person)[T.McCain_2008]         0.0640      0.002     38.759      0.000       0.061       0.067
C(person)[T.McGovern_1972]       0.0055      0.002      3.092      0.002       0.002       0.009
C(person)[T.Mondale_1984]       -0.0052      0.000    -20.242      0.000      -0.006      -0.005
C(person)[T.Nixon_1960]         -0.0216      0.001    -28.415      0.000      -0.023      -0.020
C(person)[T.Nixon_1968]          0.0025      0.001      4.174      0.000       0.001       0.004
C(person)[T.Nixon_1972]         -0.0216      4e-05   -540.050      0.000      -0.022      -0.022
C(person)[T.Obama_2008]          0.0674      0.002     36.156      0.000       0.064       0.071
C(person)[T.Obama_2012]          0.0142      0.001     15.462      0.000       0.012       0.016
C(person)[T.Reagan_1980]         0.0077   3.27e-05    235.865      0.000       0.008       0.008
C(person)[T.Reagan_1984]        -0.0001      0.000     -0.331      0.740      -0.001       0.001
C(person)[T.Romney_2012]         0.0166      0.001     19.418      0.000       0.015       0.018
C(person)[T.Stevenson_1952]     -0.0343   9.72e-05   -352.702      0.000      -0.034      -0.034
C(person)[T.Stevenson_1956]      0.0004      0.001      0.432      0.666      -0.002       0.002
C(person)[T.Trump_2016]         -0.0149      0.002     -7.683      0.000      -0.019      -0.011
C(person)[T.Trump_2020]         -0.0003      0.000     -1.024      0.306      -0.001       0.000
Populism                         0.0018      0.003      0.538      0.591      -0.005       0.009
prior_president                 -0.0063      0.000    -19.999      0.000      -0.007      -0.006
==============================================================================
Omnibus:                      100.446   Durbin-Watson:                   1.883
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              121.717
Skew:                           0.343   Prob(JB):                     3.71e-27
Kurtosis:                       3.562   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

# Contructed

In [50]:
import statsmodels.api as sm

y = df_balanced["constructed_sim_top10"]
X = sm.add_constant(df_balanced[["Populism"]])

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     constructed_sim_top10   R-squared:                       0.001
Model:                               OLS   Adj. R-squared:                  0.001
Method:                    Least Squares   F-statistic:                     3.630
Date:                   Wed, 17 Dec 2025   Prob (F-statistic):             0.0568
Time:                           18:34:48   Log-Likelihood:                 5522.1
No. Observations:                   3722   AIC:                        -1.104e+04
Df Residuals:                       3720   BIC:                        -1.103e+04
Df Model:                              1
Covariance Type:                     HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1812      0.001    137.766      0.000       0.179       0.184
Populism       0.0034      0.002      1.905      0.057   -9.83e-05       0.007
==============================================================================
Omnibus:                       34.343   Durbin-Watson:                   1.866
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.597
Skew:                           0.224   Prob(JB):                     3.07e-08
Kurtosis:                       2.851   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [51]:
import numpy as np

coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["constructed_sim_top10"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit()
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(0.003279294363427258, 0.0012257037183484871)

In [52]:
import statsmodels.api as sm

y = df_balanced["constructed_sim_top10"]

X = df_balanced[["Populism", "prior_president"]]
X = sm.add_constant(X)

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     constructed_sim_top10   R-squared:                       0.004
Model:                               OLS   Adj. R-squared:                  0.003
Method:                    Least Squares   F-statistic:                     6.713
Date:                   Wed, 17 Dec 2025   Prob (F-statistic):            0.00123
Time:                           18:34:56   Log-Likelihood:                 5527.2
No. Observations:                   3722   AIC:                        -1.105e+04
Df Residuals:                       3719   BIC:                        -1.103e+04
Df Model:                              2
Covariance Type:                     HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.1839      0.002    118.650      0.000       0.181       0.187
Populism            0.0017      0.002      0.905      0.365      -0.002       0.005
prior_president    -0.0067      0.002     -3.208      0.001      -0.011      -0.003
==============================================================================
Omnibus:                       33.030   Durbin-Watson:                   1.865
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.441
Skew:                           0.223   Prob(JB):                     5.47e-08
Kurtosis:                       2.869   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [53]:
import statsmodels.formula.api as smf

fe_person = smf.ols(
    "constructed_sim_top10 ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe_person.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     constructed_sim_top10   R-squared:                       0.058
Model:                               OLS   Adj. R-squared:                  0.050
Method:                    Least Squares   F-statistic:                     4.570
Date:                   Wed, 17 Dec 2025   Prob (F-statistic):             0.0400
Time:                           18:35:01   Log-Likelihood:                 5632.4
No. Observations:                   3722   AIC:                        -1.119e+04
Df Residuals:                       3687   BIC:                        -1.098e+04
Df Model:                             34
Covariance Type:                 cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.1925      0.001    189.972      0.000       0.191       0.194
C(person)[T.Bush_1988]          -0.0107      0.001    -18.392      0.000      -0.012      -0.010
C(person)[T.Bush_1992]          -0.0245      0.001    -31.472      0.000      -0.026      -0.023
C(person)[T.Bush_2004]          -0.0126      0.001    -18.561      0.000      -0.014      -0.011
C(person)[T.Carter_1976]         0.0008      0.001      0.901      0.367      -0.001       0.002
C(person)[T.Carter_1980]        -0.0153      0.000    -30.756      0.000      -0.016      -0.014
C(person)[T.Clinton_1992]       -0.0241      0.001    -42.377      0.000      -0.025      -0.023
C(person)[T.Clinton_1996]       -0.0086      0.000    -19.117      0.000      -0.009      -0.008
C(person)[T.Clinton_2016]       -0.0295      0.000   -218.347      0.000      -0.030      -0.029
C(person)[T.Dole_1996]          -0.0244      0.000    -55.767      0.000      -0.025      -0.024
C(person)[T.Dukakis_1988]       -0.0134      0.001    -26.460      0.000      -0.014      -0.012
C(person)[T.Eisenhower_1952]     0.0116      0.001      7.895      0.000       0.009       0.015
C(person)[T.Eisenhower_1956]     0.0427      0.000    182.326      0.000       0.042       0.043
C(person)[T.Ford_1976]          -0.0062   7.96e-05    -78.208      0.000      -0.006      -0.006
C(person)[T.Gore_2000]          -0.0172      0.001    -11.798      0.000      -0.020      -0.014
C(person)[T.Humphrey_1968]      -0.0218      0.001    -36.400      0.000      -0.023      -0.021
C(person)[T.Johnson_1964]        0.0155      0.001     28.658      0.000       0.014       0.017
C(person)[T.Kennedy_1960]        0.0054      0.001      6.635      0.000       0.004       0.007
C(person)[T.Kerry_2004]         -0.0299      0.001    -30.682      0.000      -0.032      -0.028
C(person)[T.McCain_2008]         0.0107      0.001      7.320      0.000       0.008       0.014
C(person)[T.McGovern_1972]      -0.0039      0.002     -2.500      0.012      -0.007      -0.001
C(person)[T.Mondale_1984]       -0.0120      0.000    -53.207      0.000      -0.012      -0.012
C(person)[T.Nixon_1960]         -0.0083      0.001    -12.350      0.000      -0.010      -0.007
C(person)[T.Nixon_1968]          0.0136      0.001     25.394      0.000       0.013       0.015
C(person)[T.Nixon_1972]          0.0064   3.52e-05    180.719      0.000       0.006       0.006
C(person)[T.Obama_2008]          0.0008      0.002      0.501      0.616      -0.002       0.004
C(person)[T.Obama_2012]         -0.0071      0.001     -8.764      0.000      -0.009      -0.006
C(person)[T.Reagan_1980]        -0.0148   2.88e-05   -514.415      0.000      -0.015      -0.015
C(person)[T.Reagan_1984]         0.0042      0.000     11.614      0.000       0.003       0.005
C(person)[T.Romney_2012]        -0.0162      0.001    -21.413      0.000      -0.018      -0.015
C(person)[T.Stevenson_1952]     -0.0150   8.56e-05   -174.857      0.000      -0.015      -0.015
C(person)[T.Stevenson_1956]     -0.0097      0.001    -10.769      0.000      -0.011      -0.008
C(person)[T.Trump_2016]         -0.0070      0.002     -4.122      0.000      -0.010      -0.004
C(person)[T.Trump_2020]         -0.0037      0.000    -17.005      0.000      -0.004      -0.003
Populism                        -0.0018      0.003     -0.615      0.539      -0.008       0.004
prior_president                 -0.0092      0.000    -32.911      0.000      -0.010      -0.009
==============================================================================
Omnibus:                       18.092   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               18.145
Skew:                           0.161   Prob(JB):                     0.000115
Kurtosis:                       2.886   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '