In [39]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib as mpl
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import json

mpl.rcParams.update({
    'axes.titlesize'   : 0,        # no title
    'axes.labelsize'   : 14,       # x and y axis labels
    'xtick.labelsize'  : 12,       # x tick labels
    'ytick.labelsize'  : 12,       # y tick labels
    'legend.fontsize'  : 12,
    'font.size'        : 12,      
})

In [40]:
df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

/tmp/ipykernel_4691/2256054893.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/main_data.csv", encoding="utf-8")

In [41]:
# ============================================================
# Lexicon counting pipeline (single words + multiword phrases)
# for MULTIPLE vocabularies, in a Jupyter notebook
# ============================================================

import re
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()

TEXT_COL = "text"   # change if needed

# ------------------------------------------------------------------
# 0) CONFIG: add all your vocab files here (name -> csv path)
# ------------------------------------------------------------------
LEXICONS = {
    "scapegoating": "scapegoating_vocabulary.csv",
    "scapegoating_them": "scapegoating_them.csv",
    "scapegoating_implicit": "scapegoating_implicit.csv",
    "victimism_us": "victimism_us.csv",
    "victimism_me": "victimism_me.csv",
    "victimism_general": "victimism_general.csv",
}

# If you have a stable id column you like to inspect later:
ID_COLS_TO_SHOW = ["speech_par_id", "name_date"]  # adjust or set []


# ------------------------------------------------------------------
# 1) Helper: load + repair a lexicon file robustly into a DataFrame
# ------------------------------------------------------------------
def load_lexicon_df(path: str) -> pd.DataFrame:
    """
    Robustly load a lexicon CSV that might be:
    - well-formed with a 'term' column (optionally 'category')
    - single-column where each row contains "term,category"
    - single-column with just terms

    Returns a DataFrame with at least 'term' column.
    """
    lex_raw = pd.read_csv(path, encoding="utf-8-sig", low_memory=False)

    # Strip BOM/whitespace from column names
    lex_raw.columns = [c.strip().replace("\ufeff", "") for c in lex_raw.columns]

    if lex_raw.shape[1] == 1:
        only_col = lex_raw.columns[0]
        s = lex_raw[only_col].astype(str)

        # Split only on first comma; if there is no comma, category will be NaN
        tmp = s.str.split(",", n=1, expand=True)
        if tmp.shape[1] == 1:
            tmp[1] = np.nan

        tmp.columns = ["term", "category"]

        tmp["term"] = (
            tmp["term"].astype(str)
            .str.replace('"', "", regex=False)
            .str.replace("\ufeff", "", regex=False)
            .str.strip()
        )
        tmp["category"] = (
            tmp["category"].astype(str)
            .str.replace('"', "", regex=False)
            .str.strip()
        )

        # Drop header-like / empty rows
        tmp = tmp[tmp["term"].str.lower().ne("term") & tmp["term"].ne("")]

         # Keep only non-empty terms
        tmp = tmp[tmp["term"].notna() & tmp["term"].ne("")]

         # If category is literally "nan" string, normalize it
        tmp.loc[tmp["category"].str.lower().eq("nan"), "category"] = np.nan

        lex = tmp.copy()

    else:
        # Normal CSV
        if "term" not in lex_raw.columns:
            # fallback: first column as term
            lex_raw = lex_raw.rename(columns={lex_raw.columns[0]: "term"})
        lex = lex_raw.copy()

        lex["term"] = (
            lex["term"].astype(str)
            .str.replace('"', "", regex=False)
            .str.replace("\ufeff", "", regex=False)
            .str.strip()
        )
        lex = lex[lex["term"].str.lower().ne("term") & lex["term"].ne("")]

    # Lowercase for matching, but keep original in case you want it later
    lex["term"] = lex["term"].astype(str).str.lower().str.strip()
    lex = lex.dropna(subset=["term"])

    return lex


# ------------------------------------------------------------------
# 2) Helper: build regex objects for single words + multi-word phrases
# ------------------------------------------------------------------
def build_lexicon_regex(terms: list[str]):
    """
    Returns (single_word_regex, multi_word_regex)
    - single_word_regex uses word boundaries
    - multi_word_regex matches phrases anywhere (escaped)
    """
    terms = [t.strip().lower() for t in terms if isinstance(t, str) and t.strip()]
    terms = list(pd.unique(terms))

    single_words = [t for t in terms if " " not in t]
    multi_words  = [t for t in terms if " " in t]

    single_words_escaped = [re.escape(w) for w in single_words]
    multi_words_escaped  = [re.escape(p) for p in multi_words]

    single_word_regex = (
        re.compile(r"\b(" + "|".join(single_words_escaped) + r")\b", flags=re.IGNORECASE)
        if single_words_escaped else None
    )

    # Sorting multi-words by length helps reduce some partial-match surprises
    multi_words_escaped_sorted = sorted(multi_words_escaped, key=len, reverse=True)
    multi_word_regex = (
        re.compile(r"(" + "|".join(multi_words_escaped_sorted) + r")", flags=re.IGNORECASE)
        if multi_words_escaped_sorted else None
    )

    return single_word_regex, multi_word_regex, len(single_words), len(multi_words)


# ------------------------------------------------------------------
# 3) Helper: counting functions for a given regex pair
# ------------------------------------------------------------------
def make_count_fns(single_word_regex, multi_word_regex):
    def count_total(text):
        if not isinstance(text, str) or not text:
            return 0
        single_hits = single_word_regex.findall(text) if single_word_regex else []
        multi_hits  = multi_word_regex.findall(text) if multi_word_regex else []
        return len(single_hits) + len(multi_hits)

    def count_distinct(text):
        if not isinstance(text, str) or not text:
            return 0
        single_hits = set(m.lower() for m in single_word_regex.findall(text)) if single_word_regex else set()
        multi_hits  = set(m.lower() for m in multi_word_regex.findall(text)) if multi_word_regex else set()
        return len(single_hits.union(multi_hits))

    return count_total, count_distinct


# ------------------------------------------------------------------
# 4) Word counts (for normalization)
# ------------------------------------------------------------------
if "word_count" not in df.columns:
    df["word_count"] = df[TEXT_COL].fillna("").astype(str).str.split().str.len()


# ------------------------------------------------------------------
# 5) Run for each lexicon + write columns
# ------------------------------------------------------------------
lexicon_debug = {}

for lex_name, lex_path in LEXICONS.items():
    print(f"\n=== Processing lexicon: {lex_name} ({lex_path}) ===")

    lex_df = load_lexicon_df(lex_path)
    terms = lex_df["term"].dropna().astype(str).str.lower().str.strip().unique().tolist()

    single_re, multi_re, n_single, n_multi = build_lexicon_regex(terms)
    count_total, count_distinct = make_count_fns(single_re, multi_re)

    print(f"Loaded terms: {len(terms)} | Single: {n_single} | Multi: {n_multi}")

    # Store debug info if you want to inspect later
    lexicon_debug[lex_name] = {
        "path": lex_path,
        "n_terms": len(terms),
        "n_single": n_single,
        "n_multi": n_multi,
        "preview_terms": terms[:10],
    }

    # Column names
    col_count = f"{lex_name}_count"
    col_dist  = f"{lex_name}_distinct"
    col_per100 = f"{lex_name}_per_100w"

    # Apply with progress bar
    df[col_count] = df[TEXT_COL].progress_apply(count_total)
    df[col_dist]  = df[TEXT_COL].progress_apply(count_distinct)

    # Normalize per 100 words (safe for 0 word_count)
    df[col_per100] = np.where(
        df["word_count"] > 0,
        df[col_count] / df["word_count"] * 100,
        0.0
    )

    # Quick sanity check
    print(df[[col_count, col_dist, col_per100]].describe().round(3))


# ------------------------------------------------------------------
# 6) Optional: inspect top hits for each lexicon
# ------------------------------------------------------------------
def show_top_hits(lex_name: str, n: int = 20):
    col_count = f"{lex_name}_count"
    cols = [c for c in ID_COLS_TO_SHOW if c in df.columns] + [TEXT_COL, col_count, f"{lex_name}_per_100w"]
    return df.sort_values(col_count, ascending=False)[cols].head(n)

# Example usage:
# show_top_hits("scapegoating_them", 20)
# show_top_hits("victimism_general", 20)

# ------------------------------------------------------------------
# 7) Save updated dataframe (optional)
# ------------------------------------------------------------------
# df.to_csv("prof_llm_scapegoating_with_lexicon_counts.csv", index=False)

=== Processing lexicon: scapegoating (scapegoating_vocabulary.csv) ===
Loaded terms: 20 | Single: 1 | Multi: 19

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       scapegoating_count  scapegoating_distinct  scapegoating_per_100w
count           71808.000              71808.000              71808.000
mean                0.045                  0.040                  0.050
std                 0.252                  0.205                  0.314
min                 0.000                  0.000                  0.000
25%                 0.000                  0.000                  0.000
50%                 0.000                  0.000                  0.000
75%                 0.000                  0.000                  0.000
max                 6.000                  4.000                 21.053

=== Processing lexicon: scapegoating_them (scapegoating_them.csv) ===
Loaded terms: 60 | Single: 0 | Multi: 60

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       scapegoating_them_count  scapegoating_them_distinct  \
count                71808.000                   71808.000
mean                     0.000                       0.000
std                      0.008                       0.008
min                      0.000                       0.000
25%                      0.000                       0.000
50%                      0.000                       0.000
75%                      0.000                       0.000
max                      1.000                       1.000

       scapegoating_them_per_100w
count                   71808.000
mean                        0.000
std                         0.011
min                         0.000
25%                         0.000
50%                         0.000
75%                         0.000
max                         1.786

=== Processing lexicon: scapegoating_implicit (scapegoating_implicit.csv) ===
Loaded terms: 51 | Single: 2 | Multi: 49

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       scapegoating_implicit_count  scapegoating_implicit_distinct  \
count                    71808.000                       71808.000
mean                         0.013                           0.011
std                          0.135                           0.106
min                          0.000                           0.000
25%                          0.000                           0.000
50%                          0.000                           0.000
75%                          0.000                           0.000
max                          6.000                           2.000

       scapegoating_implicit_per_100w
count                       71808.000
mean                            0.016
std                             0.199
min                             0.000
25%                             0.000
50%                             0.000
75%                             0.000
max                            17.143

=== Processing lexicon: victimism_us (victimism_us.csv) ===
Loaded terms: 51 | Single: 0 | Multi: 51

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       victimism_us_count  victimism_us_distinct  victimism_us_per_100w
count           71808.000              71808.000              71808.000
mean                0.000                  0.000                  0.000
std                 0.007                  0.007                  0.010
min                 0.000                  0.000                  0.000
25%                 0.000                  0.000                  0.000
50%                 0.000                  0.000                  0.000
75%                 0.000                  0.000                  0.000
max                 1.000                  1.000                  2.128

=== Processing lexicon: victimism_me (victimism_me.csv) ===
Loaded terms: 12 | Single: 0 | Multi: 12

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       victimism_me_count  victimism_me_distinct  victimism_me_per_100w
count           71808.000              71808.000              71808.000
mean                0.000                  0.000                  0.000
std                 0.018                  0.018                  0.019
min                 0.000                  0.000                  0.000
25%                 0.000                  0.000                  0.000
50%                 0.000                  0.000                  0.000
75%                 0.000                  0.000                  0.000
max                 1.000                  1.000                  2.273

=== Processing lexicon: victimism_general (victimism_general.csv) ===
Loaded terms: 51 | Single: 0 | Multi: 51

  0%|          | 0/71808 [00:00<?, ?it/s]

  0%|          | 0/71808 [00:00<?, ?it/s]

       victimism_general_count  victimism_general_distinct  \
count                71808.000                   71808.000
mean                     0.001                       0.001
std                      0.034                       0.032
min                      0.000                       0.000
25%                      0.000                       0.000
50%                      0.000                       0.000
75%                      0.000                       0.000
max                      2.000                       1.000

       victimism_general_per_100w
count                   71808.000
mean                        0.001
std                         0.044
min                         0.000
25%                         0.000
50%                         0.000
75%                         0.000
max                         5.263

In [6]:
df["election_year"] = df["election_date"].astype(str).str[:4].astype("Int64")

In [7]:
set(df["election_year"])

{1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020}

In [8]:
df["person"] = (
    df["person"].astype(str)
    + "_"
    + df["election_year"].astype(str)
)

In [9]:
df_pop = df[df["Populism"] == 1]
df_non = df[df["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)

Populist rows: 1861

In [10]:
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

1    1861
0    1861
Name: Populism, dtype: int64

In [11]:
df_balanced[["scapegoating_per_100w", "Populism"]].groupby("Populism").describe()

         scapegoating_per_100w                                          \
                         count      mean       std  min  25%  50%  75%
Populism
0                       1861.0  0.049843  0.289022  0.0  0.0  0.0  0.0
1                       1861.0  0.047169  0.299952  0.0  0.0  0.0  0.0


               max
Populism
0         3.797468
1         5.263158

In [12]:
import statsmodels.api as sm

y = df_balanced["scapegoating_per_100w"]
X = df_balanced[["Populism"]]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit(cov_type="HC3")
print(model.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     scapegoating_per_100w   R-squared:                       0.000
Model:                               OLS   Adj. R-squared:                 -0.000
Method:                    Least Squares   F-statistic:                   0.07665
Date:                   Sat, 17 Jan 2026   Prob (F-statistic):              0.782
Time:                           11:11:09   Log-Likelihood:                -730.71
No. Observations:                   3722   AIC:                             1465.
Df Residuals:                       3720   BIC:                             1478.
Df Model:                              1
Covariance Type:                     HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0498      0.007      7.437      0.000       0.037       0.063
Populism      -0.0027      0.010     -0.277      0.782      -0.022       0.016
==============================================================================
Omnibus:                     5322.018   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1404060.341
Skew:                           8.552   Prob(JB):                         0.00
Kurtosis:                      96.600   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [13]:
import numpy as np
coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["scapegoating_per_100w"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit(cov_type="HC3")
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(-0.003828564549517791, 0.006595415781429123)

In [14]:
import statsmodels.formula.api as smf

# Make sure types are correct
df_balanced["Populism"] = df_balanced["Populism"].astype(int)
df_balanced["prior_president"] = df_balanced["prior_president"].astype(int)

# Drop missing values in required columns
df_mixed = df_balanced.dropna(
    subset=["scapegoating_per_100w", "Populism", "prior_president", "person"]
)

In [15]:
mixed = smf.mixedlm(
    formula="scapegoating_per_100w ~ Populism + prior_president",
    data=df_mixed,
    groups=df_mixed["person"]
)

mixed_res = mixed.fit(method="lbfgs")
print(mixed_res.summary())

                 Mixed Linear Model Regression Results
=======================================================================
Model:              MixedLM  Dependent Variable:  scapegoating_per_100w
No. Observations:   3722     Method:              REML
No. Groups:         34       Scale:               0.0858
Min. group size:    17       Log-Likelihood:      inf
Max. group size:    367      Converged:           Yes
Mean group size:    109.5
-----------------------------------------------------------------------
                Coef.   Std.Err.    z    P>|z|    [0.025       0.975]
-----------------------------------------------------------------------
Intercept        0.032 316964.665  0.000 1.000  -621239.295  621239.360
Populism        -0.019      0.012 -1.575 0.115       -0.043       0.005
prior_president  0.004 637813.507  0.000 1.000 -1250091.499 1250091.506
Group Var        0.000
=======================================================================

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:1635: UserWarning: Random effects covariance is singular
  warnings.warn(msg)
/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2055: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)
/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2246: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)
/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

In [16]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

fe = smf.ols(
    "scapegoating_per_100w ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     scapegoating_per_100w   R-squared:                       0.012
Model:                               OLS   Adj. R-squared:                  0.002
Method:                    Least Squares   F-statistic:                     19.35
Date:                   Sat, 17 Jan 2026   Prob (F-statistic):           0.000107
Time:                           11:11:10   Log-Likelihood:                -709.11
No. Observations:                   3722   AIC:                             1488.
Df Residuals:                       3687   BIC:                             1706.
Df Model:                             34
Covariance Type:                 cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.0205      0.004      5.078      0.000       0.013       0.028
C(person)[T.Bush_1988]          -0.0177      0.002     -7.631      0.000      -0.022      -0.013
C(person)[T.Bush_1992]          -0.0046      0.003     -1.502      0.133      -0.011       0.001
C(person)[T.Bush_2004]           0.0282      0.003     10.471      0.000       0.023       0.033
C(person)[T.Carter_1976]         0.0795      0.003     23.140      0.000       0.073       0.086
C(person)[T.Carter_1980]        -0.0398      0.002    -20.128      0.000      -0.044      -0.036
C(person)[T.Clinton_1992]        0.0156      0.002      6.901      0.000       0.011       0.020
C(person)[T.Clinton_1996]        0.0600      0.002     33.464      0.000       0.056       0.063
C(person)[T.Clinton_2016]        0.0187      0.001     34.704      0.000       0.018       0.020
C(person)[T.Dole_1996]           0.0310      0.002     17.834      0.000       0.028       0.034
C(person)[T.Dukakis_1988]        0.0330      0.002     16.400      0.000       0.029       0.037
C(person)[T.Eisenhower_1952]     0.0799      0.006     13.622      0.000       0.068       0.091
C(person)[T.Eisenhower_1956]     0.0157      0.001     16.818      0.000       0.014       0.018
C(person)[T.Ford_1976]           0.0029      0.000      9.030      0.000       0.002       0.003
C(person)[T.Gore_2000]          -0.0047      0.006     -0.810      0.418      -0.016       0.007
C(person)[T.Humphrey_1968]      -0.0123      0.002     -5.166      0.000      -0.017      -0.008
C(person)[T.Johnson_1964]        0.0143      0.002      6.665      0.000       0.010       0.019
C(person)[T.Kennedy_1960]       -0.0026      0.003     -0.804      0.421      -0.009       0.004
C(person)[T.Kerry_2004]          0.0632      0.004     16.277      0.000       0.056       0.071
C(person)[T.McCain_2008]         0.0442      0.006      7.642      0.000       0.033       0.056
C(person)[T.McGovern_1972]       0.0429      0.006      6.936      0.000       0.031       0.055
C(person)[T.Mondale_1984]        0.0005      0.001      0.524      0.600      -0.001       0.002
C(person)[T.Nixon_1960]          0.0251      0.003      9.422      0.000       0.020       0.030
C(person)[T.Nixon_1968]          0.1506      0.002     70.568      0.000       0.146       0.155
C(person)[T.Nixon_1972]         -0.0364      0.000   -259.719      0.000      -0.037      -0.036
C(person)[T.Obama_2008]          0.0822      0.007     12.581      0.000       0.069       0.095
C(person)[T.Obama_2012]         -0.0004      0.003     -0.125      0.901      -0.007       0.006
C(person)[T.Reagan_1980]         0.0785      0.000    685.086      0.000       0.078       0.079
C(person)[T.Reagan_1984]         0.0064      0.001      4.476      0.000       0.004       0.009
C(person)[T.Romney_2012]         0.0109      0.003      3.636      0.000       0.005       0.017
C(person)[T.Stevenson_1952]      0.0136      0.000     39.837      0.000       0.013       0.014
C(person)[T.Stevenson_1956]      0.0226      0.004      6.284      0.000       0.016       0.030
C(person)[T.Trump_2016]          0.0427      0.007      6.272      0.000       0.029       0.056
C(person)[T.Trump_2020]         -0.0254      0.001    -29.551      0.000      -0.027      -0.024
Populism                        -0.0191      0.012     -1.602      0.109      -0.043       0.004
prior_president                  0.0208      0.001     18.798      0.000       0.019       0.023
==============================================================================
Omnibus:                     5290.578   Durbin-Watson:                   1.969
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1384000.982
Skew:                           8.453   Prob(JB):                         0.00
Kurtosis:                      95.943   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

In [17]:
df.to_csv("prof_llm_scapegoating.csv", encoding="utf-8", index=False)

In [18]:
dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_scapegoating_with_similarity.csv", encoding="utf-8")

/tmp/ipykernel_4691/2124667189.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_scapegoating_with_similarity.csv", encoding="utf-8")

In [19]:
df_pop = dfllm[dfllm["Populism"] == 1]
df_non = dfllm[dfllm["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)

Populist rows: 1861

In [20]:
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

1    1861
0    1861
Name: Populism, dtype: int64

In [21]:
df_balanced[["scapegoating_sim_top10", "scapegoating_sim_max"]].describe()
df_balanced[["scapegoating_sim_top10", "scapegoating_sim_max"]].corr()

                        scapegoating_sim_top10  scapegoating_sim_max
scapegoating_sim_top10                1.000000              0.824905
scapegoating_sim_max                  0.824905              1.000000

In [22]:
for var in ["scapegoating_sim_top10", "scapegoating_sim_max"]:
    res = smf.ols(
        f"{var} ~ Populism + prior_president + C(person)",
        data=df_balanced
    ).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})
    print(var, res.params["Populism"], res.pvalues["Populism"])

scapegoating_sim_top10 -0.004459726053408797 0.0961651408081681
scapegoating_sim_max 0.004292826611228077 0.250519194914092

In [23]:
import statsmodels.api as sm

y = df_balanced["scapegoating_sim_top10"]
X = sm.add_constant(df_balanced[["Populism"]])

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     scapegoating_sim_top10   R-squared:                       0.000
Model:                                OLS   Adj. R-squared:                  0.000
Method:                     Least Squares   F-statistic:                     1.081
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):              0.299
Time:                            11:11:13   Log-Likelihood:                 6440.9
No. Observations:                    3722   AIC:                        -1.288e+04
Df Residuals:                        3720   BIC:                        -1.287e+04
Df Model:                               1
Covariance Type:                      HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0930      0.001     95.775      0.000       0.091       0.095
Populism       0.0015      0.001      1.040      0.299      -0.001       0.004
==============================================================================
Omnibus:                       34.465   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.837
Skew:                           0.204   Prob(JB):                     1.00e-08
Kurtosis:                       3.265   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [24]:
import numpy as np

coefs = []

for seed in range(100):
    df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
    df_bal = pd.concat([df_pop, df_non_sampled])

    y = df_bal["scapegoating_sim_top10"]
    X = sm.add_constant(df_bal[["Populism"]])

    res = sm.OLS(y, X).fit()
    coefs.append(res.params["Populism"])

np.mean(coefs), np.std(coefs)

(0.0014809708895186125, 0.0010118691523932119)

In [25]:
import statsmodels.api as sm

y = df_balanced["scapegoating_sim_top10"]

X = df_balanced[["Populism", "prior_president"]]
X = sm.add_constant(X)

ols = sm.OLS(y, X).fit(cov_type="HC3")
print(ols.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     scapegoating_sim_top10   R-squared:                       0.001
Model:                                OLS   Adj. R-squared:                  0.000
Method:                     Least Squares   F-statistic:                     1.138
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):              0.321
Time:                            11:11:14   Log-Likelihood:                 6441.5
No. Observations:                    3722   AIC:                        -1.288e+04
Df Residuals:                        3719   BIC:                        -1.286e+04
Df Model:                               2
Covariance Type:                      HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.0937      0.001     79.575      0.000       0.091       0.096
Populism            0.0010      0.001      0.683      0.494      -0.002       0.004
prior_president    -0.0018      0.002     -1.108      0.268      -0.005       0.001
==============================================================================
Omnibus:                       34.023   Durbin-Watson:                   1.858
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.365
Skew:                           0.203   Prob(JB):                     1.27e-08
Kurtosis:                       3.265   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [26]:
import statsmodels.formula.api as smf

fe_person = smf.ols(
    "scapegoating_sim_top10 ~ Populism + prior_president + C(person)",
    data=df_balanced
).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

print(fe_person.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     scapegoating_sim_top10   R-squared:                       0.082
Model:                                OLS   Adj. R-squared:                  0.074
Method:                     Least Squares   F-statistic:                     1.928
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):              0.174
Time:                            11:11:14   Log-Likelihood:                 6599.6
No. Observations:                    3722   AIC:                        -1.313e+04
Df Residuals:                        3687   BIC:                        -1.291e+04
Df Model:                              34
Covariance Type:                  cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.1050      0.001    116.148      0.000       0.103       0.107
C(person)[T.Bush_1988]          -0.0199      0.001    -38.237      0.000      -0.021      -0.019
C(person)[T.Bush_1992]          -0.0165      0.001    -23.823      0.000      -0.018      -0.015
C(person)[T.Bush_2004]           0.0098      0.001     16.278      0.000       0.009       0.011
C(person)[T.Carter_1976]        -0.0233      0.001    -30.170      0.000      -0.025      -0.022
C(person)[T.Carter_1980]        -0.0123      0.000    -27.828      0.000      -0.013      -0.011
C(person)[T.Clinton_1992]       -0.0364      0.001    -71.757      0.000      -0.037      -0.035
C(person)[T.Clinton_1996]       -0.0130      0.000    -32.409      0.000      -0.014      -0.012
C(person)[T.Clinton_2016]       -0.0205      0.000   -170.062      0.000      -0.021      -0.020
C(person)[T.Dole_1996]          -0.0166      0.000    -42.664      0.000      -0.017      -0.016
C(person)[T.Dukakis_1988]       -0.0143      0.000    -31.622      0.000      -0.015      -0.013
C(person)[T.Eisenhower_1952]    -0.0002      0.001     -0.132      0.895      -0.003       0.002
C(person)[T.Eisenhower_1956]     0.0223      0.000    106.419      0.000       0.022       0.023
C(person)[T.Ford_1976]          -0.0030   7.11e-05    -41.663      0.000      -0.003      -0.003
C(person)[T.Gore_2000]          -0.0183      0.001    -14.039      0.000      -0.021      -0.016
C(person)[T.Humphrey_1968]      -0.0157      0.001    -29.477      0.000      -0.017      -0.015
C(person)[T.Johnson_1964]        0.0058      0.000     12.043      0.000       0.005       0.007
C(person)[T.Kennedy_1960]       -0.0233      0.001    -32.044      0.000      -0.025      -0.022
C(person)[T.Kerry_2004]         -0.0294      0.001    -33.792      0.000      -0.031      -0.028
C(person)[T.McCain_2008]         0.0113      0.001      8.728      0.000       0.009       0.014
C(person)[T.McGovern_1972]       0.0005      0.001      0.328      0.743      -0.002       0.003
C(person)[T.Mondale_1984]       -0.0059      0.000    -29.330      0.000      -0.006      -0.006
C(person)[T.Nixon_1960]         -0.0228      0.001    -38.179      0.000      -0.024      -0.022
C(person)[T.Nixon_1968]         -0.0059      0.000    -12.415      0.000      -0.007      -0.005
C(person)[T.Nixon_1972]         -0.0153   3.14e-05   -485.467      0.000      -0.015      -0.015
C(person)[T.Obama_2008]         -0.0152      0.001    -10.375      0.000      -0.018      -0.012
C(person)[T.Obama_2012]         -0.0035      0.001     -4.789      0.000      -0.005      -0.002
C(person)[T.Reagan_1980]         0.0067   2.57e-05    259.054      0.000       0.007       0.007
C(person)[T.Reagan_1984]         0.0067      0.000     20.730      0.000       0.006       0.007
C(person)[T.Romney_2012]        -0.0106      0.001    -15.776      0.000      -0.012      -0.009
C(person)[T.Stevenson_1952]     -0.0121   7.64e-05   -158.424      0.000      -0.012      -0.012
C(person)[T.Stevenson_1956]     -0.0072      0.001     -8.973      0.000      -0.009      -0.006
C(person)[T.Trump_2016]          0.0115      0.002      7.510      0.000       0.008       0.014
C(person)[T.Trump_2020]          0.0089      0.000     46.379      0.000       0.009       0.009
Populism                        -0.0045      0.003     -1.664      0.096      -0.010       0.001
prior_president                 -0.0101      0.000    -40.536      0.000      -0.011      -0.010
==============================================================================
Omnibus:                       32.422   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.525
Skew:                           0.198   Prob(JB):                     3.18e-08
Kurtosis:                       3.256   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

In [27]:
dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_scapegoating_with_similarity_multi.csv", encoding="utf-8")

/tmp/ipykernel_4691/1457127885.py:1: DtypeWarning: Columns (0,4,5,21) have mixed types. Specify dtype option on import or set low_memory=False.
  dfllm = pd.read_csv("/home/scc/sergio.zanotto/bin/badmanners/vulgarity/prof_llm_scapegoating_with_similarity_multi.csv", encoding="utf-8")

In [28]:
df_pop = dfllm[dfllm["Populism"] == 1]
df_non = dfllm[dfllm["Populism"] == 0]

n_pop = len(df_pop)
print("Populist rows:", n_pop)

Populist rows: 1861

In [29]:
df_non_sampled = df_non.sample(
    n=n_pop,
    random_state=42  # for reproducibility
)

# Combine
df_balanced = pd.concat([df_pop, df_non_sampled], axis=0).reset_index(drop=True)

print(df_balanced["Populism"].value_counts())

1    1861
0    1861
Name: Populism, dtype: int64

In [30]:
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

# -------------------------------------------------------------------
# CONFIG: which dependent variables to run the exact same pipeline on
# -------------------------------------------------------------------
DVS = [
    "victimism_us_sim_top10",
    "victimism_me_sim_top10",
    "scapegoating_them_sim_top10",
]

# Optional: your downsampling pieces (only used in the seed loop).
# Assumes you already have these from before:
# df_pop, df_non, n_pop
DO_SEED_LOOP = True
N_SEEDS = 100


def run_all_models(dv: str, df_balanced):
    print("\n" + "=" * 80)
    print(f"DV = {dv}")
    print("=" * 80)

    # ----------------------------
    # 1) OLS: DV ~ Populism
    # ----------------------------
    y = df_balanced[dv]
    X = sm.add_constant(df_balanced[["Populism"]])
    ols_hc3 = sm.OLS(y, X).fit(cov_type="HC3")
    print("\n[1] OLS (HC3):", f"{dv} ~ Populism")
    print(ols_hc3.summary())

    # ----------------------------
    # 2) Seed loop: downsample non-populists repeatedly, store Populism coef
    # ----------------------------
    if DO_SEED_LOOP:
        coefs = []
        for seed in range(N_SEEDS):
            df_non_sampled = df_non.sample(n=n_pop, random_state=seed)
            df_bal = pd.concat([df_pop, df_non_sampled], ignore_index=True)

            y_seed = df_bal[dv]
            X_seed = sm.add_constant(df_bal[["Populism"]])
            res_seed = sm.OLS(y_seed, X_seed).fit()
            coefs.append(res_seed.params["Populism"])

        coefs = np.array(coefs, dtype=float)
        print(f"\n[2] Seed loop (N={N_SEEDS}) Populism coef:")
        print("    mean =", coefs.mean())
        print("    std  =", coefs.std(ddof=1))
        print("    min  =", coefs.min())
        print("    max  =", coefs.max())

    # ----------------------------
    # 3) OLS: DV ~ Populism + prior_president
    # ----------------------------
    X2 = sm.add_constant(df_balanced[["Populism", "prior_president"]])
    ols2_hc3 = sm.OLS(y, X2).fit(cov_type="HC3")
    print("\n[3] OLS (HC3):", f"{dv} ~ Populism + prior_president")
    print(ols2_hc3.summary())

    # ----------------------------
    # 4) Person FE: DV ~ Populism + prior_president + C(person)
    #    Cluster SE by person (same as your example)
    # ----------------------------
    fe_person = smf.ols(
        f"{dv} ~ Populism + prior_president + C(person)",
        data=df_balanced
    ).fit(cov_type="cluster", cov_kwds={"groups": df_balanced["person"]})

    print("\n[4] Person FE (clustered by person):",
          f"{dv} ~ Populism + prior_president + C(person)")
    print(fe_person.summary())

    # Return fitted objects if you want to store them
    return {
        "ols_hc3": ols_hc3,
        "ols2_hc3": ols2_hc3,
        "fe_person": fe_person,
        # seed coefs not returned unless you want them
    }


# -------------------------------------------------------------------
# RUN
# -------------------------------------------------------------------
results = {}
for dv in DVS:
    results[dv] = run_all_models(dv, df_balanced)

================================================================================
DV = victimism_us_sim_top10
================================================================================

[1] OLS (HC3): victimism_us_sim_top10 ~ Populism
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_us_sim_top10   R-squared:                       0.001
Model:                                OLS   Adj. R-squared:                  0.001
Method:                     Least Squares   F-statistic:                     3.235
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):             0.0722
Time:                            11:19:42   Log-Likelihood:                 5282.8
No. Observations:                    3722   AIC:                        -1.056e+04
Df Residuals:                        3720   BIC:                        -1.055e+04
Df Model:                               1
Covariance Type:                      HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2328      0.001    164.491      0.000       0.230       0.236
Populism       0.0035      0.002      1.799      0.072      -0.000       0.007
==============================================================================
Omnibus:                       12.234   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               12.274
Skew:                           0.140   Prob(JB):                      0.00216
Kurtosis:                       3.018   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

[2] Seed loop (N=100) Populism coef:
    mean = 0.0033216579799559966
    std  = 0.0013264784003876604
    min  = -0.000406285843098194
    max  = 0.006610125698546313

[3] OLS (HC3): victimism_us_sim_top10 ~ Populism + prior_president
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_us_sim_top10   R-squared:                       0.001
Model:                                OLS   Adj. R-squared:                  0.000
Method:                     Least Squares   F-statistic:                     1.623
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):              0.197
Time:                            11:19:42   Log-Likelihood:                 5282.8
No. Observations:                    3722   AIC:                        -1.056e+04
Df Residuals:                        3719   BIC:                        -1.054e+04
Df Model:                               2
Covariance Type:                      HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.2327      0.002    140.294      0.000       0.229       0.236
Populism            0.0035      0.002      1.746      0.081      -0.000       0.007
prior_president     0.0002      0.002      0.084      0.933      -0.004       0.005
==============================================================================
Omnibus:                       12.168   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               12.208
Skew:                           0.140   Prob(JB):                      0.00223
Kurtosis:                       3.017   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

[4] Person FE (clustered by person): victimism_us_sim_top10 ~ Populism + prior_president + C(person)
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_us_sim_top10   R-squared:                       0.049
Model:                                OLS   Adj. R-squared:                  0.041
Method:                     Least Squares   F-statistic:                     12.66
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):            0.00116
Time:                            11:19:42   Log-Likelihood:                 5375.4
No. Observations:                    3722   AIC:                        -1.068e+04
Df Residuals:                        3687   BIC:                        -1.046e+04
Df Model:                              34
Covariance Type:                  cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.2478      0.001    229.136      0.000       0.246       0.250
C(person)[T.Bush_1988]          -0.0203      0.001    -32.566      0.000      -0.022      -0.019
C(person)[T.Bush_1992]          -0.0286      0.001    -34.467      0.000      -0.030      -0.027
C(person)[T.Bush_2004]          -0.0133      0.001    -18.392      0.000      -0.015      -0.012
C(person)[T.Carter_1976]        -0.0029      0.001     -3.122      0.002      -0.005      -0.001
C(person)[T.Carter_1980]        -0.0167      0.001    -31.581      0.000      -0.018      -0.016
C(person)[T.Clinton_1992]       -0.0248      0.001    -40.909      0.000      -0.026      -0.024
C(person)[T.Clinton_1996]       -0.0023      0.000     -4.700      0.000      -0.003      -0.001
C(person)[T.Clinton_2016]       -0.0307      0.000   -212.600      0.000      -0.031      -0.030
C(person)[T.Dole_1996]          -0.0304      0.000    -65.223      0.000      -0.031      -0.029
C(person)[T.Dukakis_1988]       -0.0206      0.001    -38.113      0.000      -0.022      -0.020
C(person)[T.Eisenhower_1952]     0.0037      0.002      2.324      0.020       0.001       0.007
C(person)[T.Eisenhower_1956]     0.0352      0.000    140.898      0.000       0.035       0.036
C(person)[T.Ford_1976]           0.0074    8.5e-05     86.826      0.000       0.007       0.008
C(person)[T.Gore_2000]          -0.0199      0.002    -12.773      0.000      -0.023      -0.017
C(person)[T.Humphrey_1968]      -0.0313      0.001    -48.951      0.000      -0.033      -0.030
C(person)[T.Johnson_1964]        0.0086      0.001     14.933      0.000       0.007       0.010
C(person)[T.Kennedy_1960]       -0.0066      0.001     -7.570      0.000      -0.008      -0.005
C(person)[T.Kerry_2004]         -0.0295      0.001    -28.333      0.000      -0.032      -0.027
C(person)[T.McCain_2008]        -0.0125      0.002     -8.034      0.000      -0.016      -0.009
C(person)[T.McGovern_1972]      -0.0065      0.002     -3.936      0.000      -0.010      -0.003
C(person)[T.Mondale_1984]       -0.0131      0.000    -54.610      0.000      -0.014      -0.013
C(person)[T.Nixon_1960]         -0.0146      0.001    -20.410      0.000      -0.016      -0.013
C(person)[T.Nixon_1968]          0.0013      0.001      2.193      0.028       0.000       0.002
C(person)[T.Nixon_1972]         -0.0106   3.76e-05   -282.654      0.000      -0.011      -0.011
C(person)[T.Obama_2008]          0.0004      0.002      0.231      0.817      -0.003       0.004
C(person)[T.Obama_2012]          0.0001      0.001      0.125      0.900      -0.002       0.002
C(person)[T.Reagan_1980]        -0.0134   3.07e-05   -434.585      0.000      -0.013      -0.013
C(person)[T.Reagan_1984]         0.0214      0.000     55.737      0.000       0.021       0.022
C(person)[T.Romney_2012]        -0.0210      0.001    -26.030      0.000      -0.023      -0.019
C(person)[T.Stevenson_1952]     -0.0188   9.14e-05   -205.866      0.000      -0.019      -0.019
C(person)[T.Stevenson_1956]     -0.0142      0.001    -14.730      0.000      -0.016      -0.012
C(person)[T.Trump_2016]         -0.0215      0.002    -11.763      0.000      -0.025      -0.018
C(person)[T.Trump_2020]         -0.0116      0.000    -50.132      0.000      -0.012      -0.011
Populism                         0.0002      0.003      0.067      0.946      -0.006       0.006
prior_president                 -0.0103      0.000    -34.726      0.000      -0.011      -0.010
==============================================================================
Omnibus:                        7.889   Durbin-Watson:                   1.903
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                7.872
Skew:                           0.112   Prob(JB):                       0.0195
Kurtosis:                       3.021   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

================================================================================
DV = victimism_me_sim_top10
================================================================================

[1] OLS (HC3): victimism_me_sim_top10 ~ Populism
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_me_sim_top10   R-squared:                       0.006
Model:                                OLS   Adj. R-squared:                  0.006
Method:                     Least Squares   F-statistic:                     22.50
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):           2.18e-06
Time:                            11:19:42   Log-Likelihood:                 5383.7
No. Observations:                    3722   AIC:                        -1.076e+04
Df Residuals:                        3720   BIC:                        -1.075e+04
Df Model:                               1
Covariance Type:                      HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0658      0.001     49.049      0.000       0.063       0.068
Populism       0.0089      0.002      4.744      0.000       0.005       0.013
==============================================================================
Omnibus:                       22.615   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.973
Skew:                           0.191   Prob(JB):                     1.03e-05
Kurtosis:                       2.948   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

[2] Seed loop (N=100) Populism coef:
    mean = 0.00850188002578326
    std  = 0.0013438189723617606
    min  = 0.005396395658608966
    max  = 0.011292396868609464

[3] OLS (HC3): victimism_me_sim_top10 ~ Populism + prior_president
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_me_sim_top10   R-squared:                       0.006
Model:                                OLS   Adj. R-squared:                  0.006
Method:                     Least Squares   F-statistic:                     11.35
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):           1.22e-05
Time:                            11:19:43   Log-Likelihood:                 5383.8
No. Observations:                    3722   AIC:                        -1.076e+04
Df Residuals:                        3719   BIC:                        -1.074e+04
Df Model:                               2
Covariance Type:                      HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.0653      0.002     40.494      0.000       0.062       0.068
Populism            0.0092      0.002      4.662      0.000       0.005       0.013
prior_president     0.0012      0.002      0.540      0.589      -0.003       0.006
==============================================================================
Omnibus:                       22.354   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.705
Skew:                           0.190   Prob(JB):                     1.17e-05
Kurtosis:                       2.949   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

[4] Person FE (clustered by person): victimism_me_sim_top10 ~ Populism + prior_president + C(person)
                              OLS Regression Results
==================================================================================
Dep. Variable:     victimism_me_sim_top10   R-squared:                       0.101
Model:                                OLS   Adj. R-squared:                  0.093
Method:                     Least Squares   F-statistic:                     2.487
Date:                    Sat, 17 Jan 2026   Prob (F-statistic):              0.124
Time:                            11:19:43   Log-Likelihood:                 5571.0
No. Observations:                    3722   AIC:                        -1.107e+04
Df Residuals:                        3687   BIC:                        -1.085e+04
Df Model:                              34
Covariance Type:                  cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.0727      0.001     50.117      0.000       0.070       0.076
C(person)[T.Bush_1988]          -0.0235      0.001    -28.111      0.000      -0.025      -0.022
C(person)[T.Bush_1992]          -0.0287      0.001    -25.799      0.000      -0.031      -0.027
C(person)[T.Bush_2004]           0.0060      0.001      6.249      0.000       0.004       0.008
C(person)[T.Carter_1976]        -0.0069      0.001     -5.588      0.000      -0.009      -0.004
C(person)[T.Carter_1980]        -0.0152      0.001    -21.359      0.000      -0.017      -0.014
C(person)[T.Clinton_1992]       -0.0272      0.001    -33.442      0.000      -0.029      -0.026
C(person)[T.Clinton_1996]       -0.0086      0.001    -13.267      0.000      -0.010      -0.007
C(person)[T.Clinton_2016]       -0.0161      0.000    -83.095      0.000      -0.016      -0.016
C(person)[T.Dole_1996]          -0.0143      0.001    -22.955      0.000      -0.016      -0.013
C(person)[T.Dukakis_1988]       -0.0196      0.001    -27.018      0.000      -0.021      -0.018
C(person)[T.Eisenhower_1952]     0.0254      0.002     12.044      0.000       0.021       0.030
C(person)[T.Eisenhower_1956]     0.0423      0.000    125.988      0.000       0.042       0.043
C(person)[T.Ford_1976]          -0.0158      0.000   -139.053      0.000      -0.016      -0.016
C(person)[T.Gore_2000]          -0.0024      0.002     -1.153      0.249      -0.007       0.002
C(person)[T.Humphrey_1968]      -0.0013      0.001     -1.471      0.141      -0.003       0.000
C(person)[T.Johnson_1964]        0.0197      0.001     25.539      0.000       0.018       0.021
C(person)[T.Kennedy_1960]       -0.0083      0.001     -7.113      0.000      -0.011      -0.006
C(person)[T.Kerry_2004]         -0.0365      0.001    -26.146      0.000      -0.039      -0.034
C(person)[T.McCain_2008]         0.0098      0.002      4.728      0.000       0.006       0.014
C(person)[T.McGovern_1972]      -0.0115      0.002     -5.153      0.000      -0.016      -0.007
C(person)[T.Mondale_1984]       -0.0081      0.000    -25.083      0.000      -0.009      -0.007
C(person)[T.Nixon_1960]         -0.0121      0.001    -12.627      0.000      -0.014      -0.010
C(person)[T.Nixon_1968]         -0.0062      0.001     -8.082      0.000      -0.008      -0.005
C(person)[T.Nixon_1972]         -0.0194   5.04e-05   -385.899      0.000      -0.020      -0.019
C(person)[T.Obama_2008]         -0.0213      0.002     -9.078      0.000      -0.026      -0.017
C(person)[T.Obama_2012]          0.0015      0.001      1.300      0.193      -0.001       0.004
C(person)[T.Reagan_1980]        -0.0250   4.12e-05   -606.602      0.000      -0.025      -0.025
C(person)[T.Reagan_1984]        -0.0070      0.001    -13.666      0.000      -0.008      -0.006
C(person)[T.Romney_2012]        -0.0366      0.001    -33.902      0.000      -0.039      -0.034
C(person)[T.Stevenson_1952]      0.0081      0.000     66.374      0.000       0.008       0.008
C(person)[T.Stevenson_1956]     -0.0303      0.001    -23.413      0.000      -0.033      -0.028
C(person)[T.Trump_2016]          0.0108      0.002      4.412      0.000       0.006       0.016
C(person)[T.Trump_2020]          0.0224      0.000     72.283      0.000       0.022       0.023
Populism                         0.0051      0.004      1.191      0.234      -0.003       0.014
prior_president                 -0.0028      0.000     -7.112      0.000      -0.004      -0.002
==============================================================================
Omnibus:                       26.168   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.577
Skew:                           0.207   Prob(JB):                     1.69e-06
Kurtosis:                       3.020   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

================================================================================
DV = scapegoating_them_sim_top10
================================================================================

[1] OLS (HC3): scapegoating_them_sim_top10 ~ Populism
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     scapegoating_them_sim_top10   R-squared:                       0.016
Model:                                     OLS   Adj. R-squared:                  0.016
Method:                          Least Squares   F-statistic:                     59.90
Date:                         Sat, 17 Jan 2026   Prob (F-statistic):           1.28e-14
Time:                                 11:19:43   Log-Likelihood:                 5489.6
No. Observations:                         3722   AIC:                        -1.098e+04
Df Residuals:                             3720   BIC:                        -1.096e+04
Df Model:                                    1
Covariance Type:                           HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2104      0.001    163.288      0.000       0.208       0.213
Populism       0.0141      0.002      7.740      0.000       0.010       0.018
==============================================================================
Omnibus:                       72.734   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               76.884
Skew:                           0.338   Prob(JB):                     2.02e-17
Kurtosis:                       3.199   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '

[2] Seed loop (N=100) Populism coef:
    mean = 0.013672233207246743
    std  = 0.0012652984126980318
    min  = 0.010347001558299387
    max  = 0.016469020657708364

[3] OLS (HC3): scapegoating_them_sim_top10 ~ Populism + prior_president
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     scapegoating_them_sim_top10   R-squared:                       0.017
Model:                                     OLS   Adj. R-squared:                  0.016
Method:                          Least Squares   F-statistic:                     31.67
Date:                         Sat, 17 Jan 2026   Prob (F-statistic):           2.30e-14
Time:                                 11:19:44   Log-Likelihood:                 5490.8
No. Observations:                         3722   AIC:                        -1.098e+04
Df Residuals:                             3719   BIC:                        -1.096e+04
Df Model:                                    2
Covariance Type:                           HC3
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.2117      0.002    135.058      0.000       0.209       0.215
Populism            0.0132      0.002      6.821      0.000       0.009       0.017
prior_president    -0.0033      0.002     -1.502      0.133      -0.008       0.001
==============================================================================
Omnibus:                       75.283   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               79.810
Skew:                           0.343   Prob(JB):                     4.67e-18
Kurtosis:                       3.210   Cond. No.                         3.42
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

[4] Person FE (clustered by person): scapegoating_them_sim_top10 ~ Populism + prior_president + C(person)
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     scapegoating_them_sim_top10   R-squared:                       0.071
Model:                                     OLS   Adj. R-squared:                  0.062
Method:                          Least Squares   F-statistic:                     4.207
Date:                         Sat, 17 Jan 2026   Prob (F-statistic):             0.0483
Time:                                 11:19:44   Log-Likelihood:                 5596.5
No. Observations:                         3722   AIC:                        -1.112e+04
Df Residuals:                             3687   BIC:                        -1.091e+04
Df Model:                                   34
Covariance Type:                       cluster
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        0.2258      0.001    217.785      0.000       0.224       0.228
C(person)[T.Bush_1988]          -0.0186      0.001    -31.100      0.000      -0.020      -0.017
C(person)[T.Bush_1992]          -0.0325      0.001    -40.910      0.000      -0.034      -0.031
C(person)[T.Bush_2004]          -0.0160      0.001    -23.073      0.000      -0.017      -0.015
C(person)[T.Carter_1976]        -0.0117      0.001    -13.280      0.000      -0.013      -0.010
C(person)[T.Carter_1980]        -0.0103      0.001    -20.339      0.000      -0.011      -0.009
C(person)[T.Clinton_1992]       -0.0228      0.001    -39.206      0.000      -0.024      -0.022
C(person)[T.Clinton_1996]       -0.0126      0.000    -27.296      0.000      -0.013      -0.012
C(person)[T.Clinton_2016]       -0.0379      0.000   -274.257      0.000      -0.038      -0.038
C(person)[T.Dole_1996]          -0.0268      0.000    -60.057      0.000      -0.028      -0.026
C(person)[T.Dukakis_1988]       -0.0052      0.001     -9.969      0.000      -0.006      -0.004
C(person)[T.Eisenhower_1952]    -0.0006      0.002     -0.430      0.667      -0.004       0.002
C(person)[T.Eisenhower_1956]     0.0250      0.000    104.299      0.000       0.025       0.025
C(person)[T.Ford_1976]           0.0063   8.15e-05     77.042      0.000       0.006       0.006
C(person)[T.Gore_2000]          -0.0171      0.001    -11.457      0.000      -0.020      -0.014
C(person)[T.Humphrey_1968]      -0.0317      0.001    -51.747      0.000      -0.033      -0.030
C(person)[T.Johnson_1964]        0.0050      0.001      9.049      0.000       0.004       0.006
C(person)[T.Kennedy_1960]       -0.0144      0.001    -17.358      0.000      -0.016      -0.013
C(person)[T.Kerry_2004]         -0.0394      0.001    -39.448      0.000      -0.041      -0.037
C(person)[T.McCain_2008]        -0.0029      0.001     -1.956      0.050      -0.006    5.67e-06
C(person)[T.McGovern_1972]    5.172e-05      0.002      0.033      0.974      -0.003       0.003
C(person)[T.Mondale_1984]       -0.0092      0.000    -39.732      0.000      -0.010      -0.009
C(person)[T.Nixon_1960]         -0.0172      0.001    -25.108      0.000      -0.019      -0.016
C(person)[T.Nixon_1968]         -0.0056      0.001    -10.289      0.000      -0.007      -0.005
C(person)[T.Nixon_1972]         -0.0105    3.6e-05   -290.141      0.000      -0.011      -0.010
C(person)[T.Obama_2008]          0.0002      0.002      0.121      0.904      -0.003       0.003
C(person)[T.Obama_2012]          0.0001      0.001      0.171      0.864      -0.001       0.002
C(person)[T.Reagan_1980]        -0.0116   2.95e-05   -394.253      0.000      -0.012      -0.012
C(person)[T.Reagan_1984]         0.0237      0.000     64.298      0.000       0.023       0.024
C(person)[T.Romney_2012]        -0.0206      0.001    -26.716      0.000      -0.022      -0.019
C(person)[T.Stevenson_1952]     -0.0146   8.76e-05   -166.172      0.000      -0.015      -0.014
C(person)[T.Stevenson_1956]      0.0028      0.001      3.051      0.002       0.001       0.005
C(person)[T.Trump_2016]         -0.0067      0.002     -3.853      0.000      -0.010      -0.003
C(person)[T.Trump_2020]          0.0104      0.000     46.866      0.000       0.010       0.011
Populism                         0.0070      0.003      2.279      0.023       0.001       0.013
prior_president                 -0.0114      0.000    -40.043      0.000      -0.012      -0.011
==============================================================================
Omnibus:                       66.011   Durbin-Watson:                   1.907
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               69.445
Skew:                           0.320   Prob(JB):                     8.32e-16
Kurtosis:                       3.195   Cond. No.                     1.70e+15
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The smallest eigenvalue is 1.83e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/jupyterhub/lib64/python3.10/site-packages/statsmodels/base/model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 35, but rank is 1
  warnings.warn('covariance of constraints does not have full '